-- mledoze/countries 데이터로 기존 country_info 행에 위도/경도 백필
-- country_name으로 매칭되는 기존 행만 UPDATE (새 행 추가 없음)

UPDATE country_info SET latitude = 12.5, longitude = -69.96666666 WHERE country_name = '아루바' AND latitude IS NULL;
UPDATE country_info SET latitude = 33, longitude = 65 WHERE country_name = '아프가니스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = -12.5, longitude = 18.5 WHERE country_name = '앙골라' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.25, longitude = -63.16666666 WHERE country_name = '앵귈라' AND latitude IS NULL;
UPDATE country_info SET latitude = 60.116667, longitude = 19.9 WHERE country_name = '올란드 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 41, longitude = 20 WHERE country_name = '알바니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 42.5, longitude = 1.5 WHERE country_name = '안도라' AND latitude IS NULL;
UPDATE country_info SET latitude = 24, longitude = 54 WHERE country_name = '아랍에미리트' AND latitude IS NULL;
UPDATE country_info SET latitude = -34, longitude = -64 WHERE country_name = '아르헨티나' AND latitude IS NULL;
UPDATE country_info SET latitude = 40, longitude = 45 WHERE country_name = '아르메니아' AND latitude IS NULL;
UPDATE country_info SET latitude = -14.33333333, longitude = -170 WHERE country_name = '아메리칸사모아' AND latitude IS NULL;
UPDATE country_info SET latitude = -90, longitude = 0 WHERE country_name = '남극' AND latitude IS NULL;
UPDATE country_info SET latitude = -49.25, longitude = 69.167 WHERE country_name = '프랑스령 남부와 남극 지역' AND latitude IS NULL;
UPDATE country_info SET latitude = 17.05, longitude = -61.8 WHERE country_name = '앤티가 바부다' AND latitude IS NULL;
UPDATE country_info SET latitude = -27, longitude = 133 WHERE country_name = '호주' AND latitude IS NULL;
UPDATE country_info SET latitude = 47.33333333, longitude = 13.33333333 WHERE country_name = '오스트리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 40.5, longitude = 47.5 WHERE country_name = '아제르바이잔' AND latitude IS NULL;
UPDATE country_info SET latitude = -3.5, longitude = 30 WHERE country_name = '부룬디' AND latitude IS NULL;
UPDATE country_info SET latitude = 50.83333333, longitude = 4 WHERE country_name = '벨기에' AND latitude IS NULL;
UPDATE country_info SET latitude = 9.5, longitude = 2.25 WHERE country_name = '베냉' AND latitude IS NULL;
UPDATE country_info SET latitude = 13, longitude = -2 WHERE country_name = '부르키나파소' AND latitude IS NULL;
UPDATE country_info SET latitude = 24, longitude = 90 WHERE country_name = '방글라데시' AND latitude IS NULL;
UPDATE country_info SET latitude = 43, longitude = 25 WHERE country_name = '불가리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 26, longitude = 50.55 WHERE country_name = '바레인' AND latitude IS NULL;
UPDATE country_info SET latitude = 24.25, longitude = -76 WHERE country_name = '바하마' AND latitude IS NULL;
UPDATE country_info SET latitude = 44, longitude = 18 WHERE country_name = '보스니아 헤르체고비나' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.5, longitude = -63.41666666 WHERE country_name = '생바르텔레미' AND latitude IS NULL;
UPDATE country_info SET latitude = -15.95, longitude = -5.72 WHERE country_name = '세인트헬레나' AND latitude IS NULL;
UPDATE country_info SET latitude = 53, longitude = 28 WHERE country_name = '벨라루스' AND latitude IS NULL;
UPDATE country_info SET latitude = 17.25, longitude = -88.75 WHERE country_name = '벨리즈' AND latitude IS NULL;
UPDATE country_info SET latitude = 32.33333333, longitude = -64.75 WHERE country_name = '버뮤다' AND latitude IS NULL;
UPDATE country_info SET latitude = -17, longitude = -65 WHERE country_name = '볼리비아' AND latitude IS NULL;
UPDATE country_info SET latitude = 12.18, longitude = -68.25 WHERE country_name = '카리브 네덜란드' AND latitude IS NULL;
UPDATE country_info SET latitude = -10, longitude = -55 WHERE country_name = '브라질' AND latitude IS NULL;
UPDATE country_info SET latitude = 13.16666666, longitude = -59.53333333 WHERE country_name = '바베이도스' AND latitude IS NULL;
UPDATE country_info SET latitude = 4.5, longitude = 114.66666666 WHERE country_name = '브루나이' AND latitude IS NULL;
UPDATE country_info SET latitude = 27.5, longitude = 90.5 WHERE country_name = '부탄' AND latitude IS NULL;
UPDATE country_info SET latitude = -54.43333333, longitude = 3.4 WHERE country_name = '부베 섬' AND latitude IS NULL;
UPDATE country_info SET latitude = -22, longitude = 24 WHERE country_name = '보츠와나' AND latitude IS NULL;
UPDATE country_info SET latitude = 7, longitude = 21 WHERE country_name = '중앙아프리카 공화국' AND latitude IS NULL;
UPDATE country_info SET latitude = 60, longitude = -95 WHERE country_name = '캐나다' AND latitude IS NULL;
UPDATE country_info SET latitude = -12.5, longitude = 96.83333333 WHERE country_name = '코코스 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 47, longitude = 8 WHERE country_name = '스위스' AND latitude IS NULL;
UPDATE country_info SET latitude = -30, longitude = -71 WHERE country_name = '칠레' AND latitude IS NULL;
UPDATE country_info SET latitude = 35, longitude = 105 WHERE country_name = '중국' AND latitude IS NULL;
UPDATE country_info SET latitude = 8, longitude = -5 WHERE country_name = '코트디부아르' AND latitude IS NULL;
UPDATE country_info SET latitude = 6, longitude = 12 WHERE country_name = '카메룬' AND latitude IS NULL;
UPDATE country_info SET latitude = 0, longitude = 25 WHERE country_name = '콩고 민주 공화국' AND latitude IS NULL;
UPDATE country_info SET latitude = -1, longitude = 15 WHERE country_name = '콩고' AND latitude IS NULL;
UPDATE country_info SET latitude = -21.23333333, longitude = -159.76666666 WHERE country_name = '쿡 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 4, longitude = -72 WHERE country_name = '콜롬비아' AND latitude IS NULL;
UPDATE country_info SET latitude = -12.16666666, longitude = 44.25 WHERE country_name = '코모로' AND latitude IS NULL;
UPDATE country_info SET latitude = 16, longitude = -24 WHERE country_name = '카보베르데' AND latitude IS NULL;
UPDATE country_info SET latitude = 10, longitude = -84 WHERE country_name = '코스타리카' AND latitude IS NULL;
UPDATE country_info SET latitude = 21.5, longitude = -80 WHERE country_name = '쿠바' AND latitude IS NULL;
UPDATE country_info SET latitude = 12.116667, longitude = -68.933333 WHERE country_name = '퀴라소' AND latitude IS NULL;
UPDATE country_info SET latitude = -10.5, longitude = 105.66666666 WHERE country_name = '크리스마스 섬' AND latitude IS NULL;
UPDATE country_info SET latitude = 19.5, longitude = -80.5 WHERE country_name = '케이맨 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 35, longitude = 33 WHERE country_name = '키프로스' AND latitude IS NULL;
UPDATE country_info SET latitude = 49.75, longitude = 15.5 WHERE country_name = '체코' AND latitude IS NULL;
UPDATE country_info SET latitude = 51, longitude = 9 WHERE country_name = '독일' AND latitude IS NULL;
UPDATE country_info SET latitude = 11.5, longitude = 43 WHERE country_name = '지부티' AND latitude IS NULL;
UPDATE country_info SET latitude = 15.41666666, longitude = -61.33333333 WHERE country_name = '도미니카 공화국' AND latitude IS NULL;
UPDATE country_info SET latitude = 56, longitude = 10 WHERE country_name = '덴마크' AND latitude IS NULL;
UPDATE country_info SET latitude = 19, longitude = -70.66666666 WHERE country_name = '도미니카 공화국' AND latitude IS NULL;
UPDATE country_info SET latitude = 28, longitude = 3 WHERE country_name = '알제리' AND latitude IS NULL;
UPDATE country_info SET latitude = -2, longitude = -77.5 WHERE country_name = '에콰도르' AND latitude IS NULL;
UPDATE country_info SET latitude = 27, longitude = 30 WHERE country_name = '이집트' AND latitude IS NULL;
UPDATE country_info SET latitude = 15, longitude = 39 WHERE country_name = '에리트레아' AND latitude IS NULL;
UPDATE country_info SET latitude = 24.5, longitude = -13 WHERE country_name = '서사하라' AND latitude IS NULL;
UPDATE country_info SET latitude = 40, longitude = -4 WHERE country_name = '스페인' AND latitude IS NULL;
UPDATE country_info SET latitude = 59, longitude = 26 WHERE country_name = '에스토니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 8, longitude = 38 WHERE country_name = '에티오피아' AND latitude IS NULL;
UPDATE country_info SET latitude = 64, longitude = 26 WHERE country_name = '핀란드' AND latitude IS NULL;
UPDATE country_info SET latitude = -18, longitude = 175 WHERE country_name = '피지' AND latitude IS NULL;
UPDATE country_info SET latitude = -51.75, longitude = -59 WHERE country_name = '포클랜드 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 46, longitude = 2 WHERE country_name = '프랑스' AND latitude IS NULL;
UPDATE country_info SET latitude = 62, longitude = -7 WHERE country_name = '페로 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 6.91666666, longitude = 158.25 WHERE country_name = '미크로네시아' AND latitude IS NULL;
UPDATE country_info SET latitude = -1, longitude = 11.75 WHERE country_name = '가봉' AND latitude IS NULL;
UPDATE country_info SET latitude = 54, longitude = -2 WHERE country_name = '영국' AND latitude IS NULL;
UPDATE country_info SET latitude = 42, longitude = 43.5 WHERE country_name = '조지아' AND latitude IS NULL;
UPDATE country_info SET latitude = 49.46666666, longitude = -2.58333333 WHERE country_name = '건지 섬' AND latitude IS NULL;
UPDATE country_info SET latitude = 8, longitude = -2 WHERE country_name = '가나' AND latitude IS NULL;
UPDATE country_info SET latitude = 36.13333333, longitude = -5.35 WHERE country_name = '지브롤터' AND latitude IS NULL;
UPDATE country_info SET latitude = 11, longitude = -10 WHERE country_name = '기니' AND latitude IS NULL;
UPDATE country_info SET latitude = 16.25, longitude = -61.583333 WHERE country_name = '과들루프' AND latitude IS NULL;
UPDATE country_info SET latitude = 13.46666666, longitude = -16.56666666 WHERE country_name = '감비아' AND latitude IS NULL;
UPDATE country_info SET latitude = 12, longitude = -15 WHERE country_name = '기니비사우' AND latitude IS NULL;
UPDATE country_info SET latitude = 2, longitude = 10 WHERE country_name = '적도 기니' AND latitude IS NULL;
UPDATE country_info SET latitude = 39, longitude = 22 WHERE country_name = '그리스' AND latitude IS NULL;
UPDATE country_info SET latitude = 12.11666666, longitude = -61.66666666 WHERE country_name = '그레나다' AND latitude IS NULL;
UPDATE country_info SET latitude = 72, longitude = -40 WHERE country_name = '그린란드' AND latitude IS NULL;
UPDATE country_info SET latitude = 15.5, longitude = -90.25 WHERE country_name = '과테말라' AND latitude IS NULL;
UPDATE country_info SET latitude = 4, longitude = -53 WHERE country_name = '프랑스령 기아나' AND latitude IS NULL;
UPDATE country_info SET latitude = 13.46666666, longitude = 144.78333333 WHERE country_name = '괌' AND latitude IS NULL;
UPDATE country_info SET latitude = 5, longitude = -59 WHERE country_name = '가이아나' AND latitude IS NULL;
UPDATE country_info SET latitude = 22.267, longitude = 114.188 WHERE country_name = '홍콩' AND latitude IS NULL;
UPDATE country_info SET latitude = -53.1, longitude = 72.51666666 WHERE country_name = '허드 맥도널드 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 15, longitude = -86.5 WHERE country_name = '온두라스' AND latitude IS NULL;
UPDATE country_info SET latitude = 45.16666666, longitude = 15.5 WHERE country_name = '크로아티아' AND latitude IS NULL;
UPDATE country_info SET latitude = 19, longitude = -72.41666666 WHERE country_name = '아이티' AND latitude IS NULL;
UPDATE country_info SET latitude = 47, longitude = 20 WHERE country_name = '헝가리' AND latitude IS NULL;
UPDATE country_info SET latitude = -5, longitude = 120 WHERE country_name = '인도네시아' AND latitude IS NULL;
UPDATE country_info SET latitude = 54.25, longitude = -4.5 WHERE country_name = '맨섬' AND latitude IS NULL;
UPDATE country_info SET latitude = 20, longitude = 77 WHERE country_name = '인도' AND latitude IS NULL;
UPDATE country_info SET latitude = -6, longitude = 71.5 WHERE country_name = '인도' AND latitude IS NULL;
UPDATE country_info SET latitude = 53, longitude = -8 WHERE country_name = '아일랜드' AND latitude IS NULL;
UPDATE country_info SET latitude = 32, longitude = 53 WHERE country_name = '이란' AND latitude IS NULL;
UPDATE country_info SET latitude = 33, longitude = 44 WHERE country_name = '이라크' AND latitude IS NULL;
UPDATE country_info SET latitude = 65, longitude = -18 WHERE country_name = '아이슬란드' AND latitude IS NULL;
UPDATE country_info SET latitude = 31.47, longitude = 35.13 WHERE country_name = '이스라엘' AND latitude IS NULL;
UPDATE country_info SET latitude = 42.83333333, longitude = 12.83333333 WHERE country_name = '이탈리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.25, longitude = -77.5 WHERE country_name = '자메이카' AND latitude IS NULL;
UPDATE country_info SET latitude = 49.25, longitude = -2.16666666 WHERE country_name = '저지 섬' AND latitude IS NULL;
UPDATE country_info SET latitude = 31, longitude = 36 WHERE country_name = '요르단' AND latitude IS NULL;
UPDATE country_info SET latitude = 36, longitude = 138 WHERE country_name = '일본' AND latitude IS NULL;
UPDATE country_info SET latitude = 48, longitude = 68 WHERE country_name = '카자흐스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = 1, longitude = 38 WHERE country_name = '케냐' AND latitude IS NULL;
UPDATE country_info SET latitude = 41, longitude = 75 WHERE country_name = '키르기스스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = 13, longitude = 105 WHERE country_name = '캄보디아' AND latitude IS NULL;
UPDATE country_info SET latitude = 1.41666666, longitude = 173 WHERE country_name = '키리바시' AND latitude IS NULL;
UPDATE country_info SET latitude = 17.33333333, longitude = -62.75 WHERE country_name = '세인트키츠 네비스' AND latitude IS NULL;
UPDATE country_info SET latitude = 37, longitude = 127.5 WHERE country_name = '한국' AND latitude IS NULL;
UPDATE country_info SET latitude = 42.666667, longitude = 21.166667 WHERE country_name = '코소보' AND latitude IS NULL;
UPDATE country_info SET latitude = 29.5, longitude = 45.75 WHERE country_name = '쿠웨이트' AND latitude IS NULL;
UPDATE country_info SET latitude = 18, longitude = 105 WHERE country_name = '라오스' AND latitude IS NULL;
UPDATE country_info SET latitude = 33.83333333, longitude = 35.83333333 WHERE country_name = '레바논' AND latitude IS NULL;
UPDATE country_info SET latitude = 6.5, longitude = -9.5 WHERE country_name = '라이베리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 25, longitude = 17 WHERE country_name = '리비아' AND latitude IS NULL;
UPDATE country_info SET latitude = 13.88333333, longitude = -60.96666666 WHERE country_name = '세인트루시아' AND latitude IS NULL;
UPDATE country_info SET latitude = 47.26666666, longitude = 9.53333333 WHERE country_name = '리히텐슈타인' AND latitude IS NULL;
UPDATE country_info SET latitude = 7, longitude = 81 WHERE country_name = '스리랑카' AND latitude IS NULL;
UPDATE country_info SET latitude = -29.5, longitude = 28.5 WHERE country_name = '레소토' AND latitude IS NULL;
UPDATE country_info SET latitude = 56, longitude = 24 WHERE country_name = '리투아니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 49.75, longitude = 6.16666666 WHERE country_name = '룩셈부르크' AND latitude IS NULL;
UPDATE country_info SET latitude = 57, longitude = 25 WHERE country_name = '라트비아' AND latitude IS NULL;
UPDATE country_info SET latitude = 22.16666666, longitude = 113.55 WHERE country_name = '마카오' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.08333333, longitude = -63.95 WHERE country_name = '생마르탱' AND latitude IS NULL;
UPDATE country_info SET latitude = 32, longitude = -5 WHERE country_name = '모로코' AND latitude IS NULL;
UPDATE country_info SET latitude = 43.73333333, longitude = 7.4 WHERE country_name = '모나코' AND latitude IS NULL;
UPDATE country_info SET latitude = 47, longitude = 29 WHERE country_name = '몰도바' AND latitude IS NULL;
UPDATE country_info SET latitude = -20, longitude = 47 WHERE country_name = '마다가스카르' AND latitude IS NULL;
UPDATE country_info SET latitude = 3.25, longitude = 73 WHERE country_name = '몰디브' AND latitude IS NULL;
UPDATE country_info SET latitude = 23, longitude = -102 WHERE country_name = '멕시코' AND latitude IS NULL;
UPDATE country_info SET latitude = 9, longitude = 168 WHERE country_name = '마셜 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 41.83333333, longitude = 22 WHERE country_name = '북마케도니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 17, longitude = -4 WHERE country_name = '말리' AND latitude IS NULL;
UPDATE country_info SET latitude = 35.83333333, longitude = 14.58333333 WHERE country_name = '몰타' AND latitude IS NULL;
UPDATE country_info SET latitude = 22, longitude = 98 WHERE country_name = '미얀마' AND latitude IS NULL;
UPDATE country_info SET latitude = 42.5, longitude = 19.3 WHERE country_name = '몬테네그로' AND latitude IS NULL;
UPDATE country_info SET latitude = 46, longitude = 105 WHERE country_name = '몽골국' AND latitude IS NULL;
UPDATE country_info SET latitude = 15.2, longitude = 145.75 WHERE country_name = '북마리아나 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = -18.25, longitude = 35 WHERE country_name = '모잠비크' AND latitude IS NULL;
UPDATE country_info SET latitude = 20, longitude = -12 WHERE country_name = '모리타니' AND latitude IS NULL;
UPDATE country_info SET latitude = 16.75, longitude = -62.2 WHERE country_name = '몬트세랫' AND latitude IS NULL;
UPDATE country_info SET latitude = 14.666667, longitude = -61 WHERE country_name = '마르티니크' AND latitude IS NULL;
UPDATE country_info SET latitude = -20.28333333, longitude = 57.55 WHERE country_name = '모리셔스' AND latitude IS NULL;
UPDATE country_info SET latitude = -13.5, longitude = 34 WHERE country_name = '말라위' AND latitude IS NULL;
UPDATE country_info SET latitude = 2.5, longitude = 112.5 WHERE country_name = '말레이시아' AND latitude IS NULL;
UPDATE country_info SET latitude = -12.83333333, longitude = 45.16666666 WHERE country_name = '마요트' AND latitude IS NULL;
UPDATE country_info SET latitude = -22, longitude = 17 WHERE country_name = '나미비아' AND latitude IS NULL;
UPDATE country_info SET latitude = -21.5, longitude = 165.5 WHERE country_name = '누벨칼레도니' AND latitude IS NULL;
UPDATE country_info SET latitude = 16, longitude = 8 WHERE country_name = '니제르' AND latitude IS NULL;
UPDATE country_info SET latitude = -29.03333333, longitude = 167.95 WHERE country_name = '노퍽 섬' AND latitude IS NULL;
UPDATE country_info SET latitude = 10, longitude = 8 WHERE country_name = '나이지리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 13, longitude = -85 WHERE country_name = '니카라과' AND latitude IS NULL;
UPDATE country_info SET latitude = -19.03333333, longitude = -169.86666666 WHERE country_name = '니우에' AND latitude IS NULL;
UPDATE country_info SET latitude = 52.5, longitude = 5.75 WHERE country_name = '네덜란드' AND latitude IS NULL;
UPDATE country_info SET latitude = 62, longitude = 10 WHERE country_name = '노르웨이' AND latitude IS NULL;
UPDATE country_info SET latitude = 28, longitude = 84 WHERE country_name = '네팔' AND latitude IS NULL;
UPDATE country_info SET latitude = -0.53333333, longitude = 166.91666666 WHERE country_name = '나우루' AND latitude IS NULL;
UPDATE country_info SET latitude = -41, longitude = 174 WHERE country_name = '뉴질랜드' AND latitude IS NULL;
UPDATE country_info SET latitude = 21, longitude = 57 WHERE country_name = '오만' AND latitude IS NULL;
UPDATE country_info SET latitude = 30, longitude = 70 WHERE country_name = '파키스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = 9, longitude = -80 WHERE country_name = '파나마' AND latitude IS NULL;
UPDATE country_info SET latitude = -25.06666666, longitude = -130.1 WHERE country_name = '핏케언 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = -10, longitude = -76 WHERE country_name = '페루' AND latitude IS NULL;
UPDATE country_info SET latitude = 13, longitude = 122 WHERE country_name = '필리핀' AND latitude IS NULL;
UPDATE country_info SET latitude = 7.5, longitude = 134.5 WHERE country_name = '팔라우' AND latitude IS NULL;
UPDATE country_info SET latitude = -6, longitude = 147 WHERE country_name = '파푸아뉴기니' AND latitude IS NULL;
UPDATE country_info SET latitude = 52, longitude = 20 WHERE country_name = '폴란드' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.25, longitude = -66.5 WHERE country_name = '푸에르토리코' AND latitude IS NULL;
UPDATE country_info SET latitude = 40, longitude = 127 WHERE country_name = '조선' AND latitude IS NULL;
UPDATE country_info SET latitude = 39.5, longitude = -8 WHERE country_name = '포르투갈' AND latitude IS NULL;
UPDATE country_info SET latitude = -23, longitude = -58 WHERE country_name = '파라과이' AND latitude IS NULL;
UPDATE country_info SET latitude = 31.9, longitude = 35.2 WHERE country_name = '팔레스타인' AND latitude IS NULL;
UPDATE country_info SET latitude = -15, longitude = -140 WHERE country_name = '프랑스령 폴리네시아' AND latitude IS NULL;
UPDATE country_info SET latitude = 25.5, longitude = 51.25 WHERE country_name = '카타르' AND latitude IS NULL;
UPDATE country_info SET latitude = -21.15, longitude = 55.5 WHERE country_name = '레위니옹' AND latitude IS NULL;
UPDATE country_info SET latitude = 46, longitude = 25 WHERE country_name = '루마니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 60, longitude = 100 WHERE country_name = '러시아' AND latitude IS NULL;
UPDATE country_info SET latitude = -2, longitude = 30 WHERE country_name = '르완다' AND latitude IS NULL;
UPDATE country_info SET latitude = 25, longitude = 45 WHERE country_name = '사우디아라비아' AND latitude IS NULL;
UPDATE country_info SET latitude = 15, longitude = 30 WHERE country_name = '수단' AND latitude IS NULL;
UPDATE country_info SET latitude = 14, longitude = -14 WHERE country_name = '세네갈' AND latitude IS NULL;
UPDATE country_info SET latitude = 1.36666666, longitude = 103.8 WHERE country_name = '싱가포르' AND latitude IS NULL;
UPDATE country_info SET latitude = -54.5, longitude = -37 WHERE country_name = '조지아' AND latitude IS NULL;
UPDATE country_info SET latitude = 78, longitude = 20 WHERE country_name = '스발바르 얀마옌 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = -8, longitude = 159 WHERE country_name = '솔로몬 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 8.5, longitude = -11.5 WHERE country_name = '시에라리온' AND latitude IS NULL;
UPDATE country_info SET latitude = 13.83333333, longitude = -88.91666666 WHERE country_name = '엘살바도르' AND latitude IS NULL;
UPDATE country_info SET latitude = 43.76666666, longitude = 12.41666666 WHERE country_name = '산마리노' AND latitude IS NULL;
UPDATE country_info SET latitude = 10, longitude = 49 WHERE country_name = '소말리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 46.83333333, longitude = -56.33333333 WHERE country_name = '생피에르 미클롱' AND latitude IS NULL;
UPDATE country_info SET latitude = 44, longitude = 21 WHERE country_name = '세르비아' AND latitude IS NULL;
UPDATE country_info SET latitude = 7, longitude = 30 WHERE country_name = '남수단' AND latitude IS NULL;
UPDATE country_info SET latitude = 1, longitude = 7 WHERE country_name = '상투메 프린시페' AND latitude IS NULL;
UPDATE country_info SET latitude = 4, longitude = -56 WHERE country_name = '수리남' AND latitude IS NULL;
UPDATE country_info SET latitude = 48.66666666, longitude = 19.5 WHERE country_name = '슬로바키아' AND latitude IS NULL;
UPDATE country_info SET latitude = 46.11666666, longitude = 14.81666666 WHERE country_name = '슬로베니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 62, longitude = 15 WHERE country_name = '스웨덴' AND latitude IS NULL;
UPDATE country_info SET latitude = -26.5, longitude = 31.5 WHERE country_name = '에스와티니' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.033333, longitude = -63.05 WHERE country_name = '신트마르턴' AND latitude IS NULL;
UPDATE country_info SET latitude = -4.58333333, longitude = 55.66666666 WHERE country_name = '세이셸' AND latitude IS NULL;
UPDATE country_info SET latitude = 35, longitude = 38 WHERE country_name = '시리아' AND latitude IS NULL;
UPDATE country_info SET latitude = 21.75, longitude = -71.58333333 WHERE country_name = '터크스 케이커스 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = 15, longitude = 19 WHERE country_name = '차드' AND latitude IS NULL;
UPDATE country_info SET latitude = 8, longitude = 1.16666666 WHERE country_name = '토고' AND latitude IS NULL;
UPDATE country_info SET latitude = 15, longitude = 100 WHERE country_name = '태국' AND latitude IS NULL;
UPDATE country_info SET latitude = 39, longitude = 71 WHERE country_name = '타지키스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = -9, longitude = -172 WHERE country_name = '토켈라우' AND latitude IS NULL;
UPDATE country_info SET latitude = 40, longitude = 60 WHERE country_name = '투르크메니스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = -8.83333333, longitude = 125.91666666 WHERE country_name = '동티모르' AND latitude IS NULL;
UPDATE country_info SET latitude = -20, longitude = -175 WHERE country_name = '통가' AND latitude IS NULL;
UPDATE country_info SET latitude = 11, longitude = -61 WHERE country_name = '트리니다드 토바고' AND latitude IS NULL;
UPDATE country_info SET latitude = 34, longitude = 9 WHERE country_name = '튀니지' AND latitude IS NULL;
UPDATE country_info SET latitude = 39, longitude = 35 WHERE country_name = '터키' AND latitude IS NULL;
UPDATE country_info SET latitude = -8, longitude = 178 WHERE country_name = '투발루' AND latitude IS NULL;
UPDATE country_info SET latitude = 23.5, longitude = 121 WHERE country_name = '대만' AND latitude IS NULL;
UPDATE country_info SET latitude = -6, longitude = 35 WHERE country_name = '탄자니아' AND latitude IS NULL;
UPDATE country_info SET latitude = 1, longitude = 32 WHERE country_name = '우간다' AND latitude IS NULL;
UPDATE country_info SET latitude = 49, longitude = 32 WHERE country_name = '우크라이나' AND latitude IS NULL;
UPDATE country_info SET latitude = 19.3, longitude = 166.633333 WHERE country_name = '미국령 군소 제도' AND latitude IS NULL;
UPDATE country_info SET latitude = -33, longitude = -56 WHERE country_name = '우루과이' AND latitude IS NULL;
UPDATE country_info SET latitude = 38, longitude = -97 WHERE country_name = '미국' AND latitude IS NULL;
UPDATE country_info SET latitude = 41, longitude = 64 WHERE country_name = '우즈베키스탄' AND latitude IS NULL;
UPDATE country_info SET latitude = 41.9, longitude = 12.45 WHERE country_name = '바티칸' AND latitude IS NULL;
UPDATE country_info SET latitude = 13.25, longitude = -61.2 WHERE country_name = '세인트빈센트 그레나딘' AND latitude IS NULL;
UPDATE country_info SET latitude = 8, longitude = -66 WHERE country_name = '베네수엘라' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.431383, longitude = -64.62305 WHERE country_name = '영국령 버진아일랜드' AND latitude IS NULL;
UPDATE country_info SET latitude = 18.35, longitude = -64.933333 WHERE country_name = '미국령 버진아일랜드' AND latitude IS NULL;
UPDATE country_info SET latitude = 16.16666666, longitude = 107.83333333 WHERE country_name = '베트남' AND latitude IS NULL;
UPDATE country_info SET latitude = -16, longitude = 167 WHERE country_name = '바누아투' AND latitude IS NULL;
UPDATE country_info SET latitude = -13.3, longitude = -176.2 WHERE country_name = '왈리스 퓌튀나' AND latitude IS NULL;
UPDATE country_info SET latitude = -13.58333333, longitude = -172.33333333 WHERE country_name = '사모아' AND latitude IS NULL;
UPDATE country_info SET latitude = 15, longitude = 48 WHERE country_name = '예멘' AND latitude IS NULL;
UPDATE country_info SET latitude = -29, longitude = 24 WHERE country_name = '남아프리카' AND latitude IS NULL;
UPDATE country_info SET latitude = -15, longitude = 30 WHERE country_name = '잠비아' AND latitude IS NULL;
UPDATE country_info SET latitude = -20, longitude = 30 WHERE country_name = '짐바브웨' AND latitude IS NULL;