-- mledoze/countries 데이터로 기존 country_info 행에 통화 코드 백필
-- country_name으로 매칭되는 기존 행만 UPDATE (새 행 추가 없음)

UPDATE country_info SET currency_code = 'AWG' WHERE country_name = '아루바' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AFN' WHERE country_name = '아프가니스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AOA' WHERE country_name = '앙골라' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '앵귈라' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '올란드 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ALL' WHERE country_name = '알바니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '안도라' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AED' WHERE country_name = '아랍에미리트' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ARS' WHERE country_name = '아르헨티나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AMD' WHERE country_name = '아르메니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '아메리칸사모아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '프랑스령 남부와 남극 지역' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '앤티가 바부다' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '호주' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '오스트리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AZN' WHERE country_name = '아제르바이잔' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BIF' WHERE country_name = '부룬디' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '벨기에' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '베냉' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '부르키나파소' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BDT' WHERE country_name = '방글라데시' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '불가리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BHD' WHERE country_name = '바레인' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BSD' WHERE country_name = '바하마' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BAM' WHERE country_name = '보스니아 헤르체고비나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '생바르텔레미' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GBP' WHERE country_name = '세인트헬레나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BYN' WHERE country_name = '벨라루스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BZD' WHERE country_name = '벨리즈' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BMD' WHERE country_name = '버뮤다' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BOB' WHERE country_name = '볼리비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '카리브 네덜란드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BRL' WHERE country_name = '브라질' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BBD' WHERE country_name = '바베이도스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BND' WHERE country_name = '브루나이' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BTN' WHERE country_name = '부탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BWP' WHERE country_name = '보츠와나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XAF' WHERE country_name = '중앙아프리카 공화국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CAD' WHERE country_name = '캐나다' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '코코스 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CHF' WHERE country_name = '스위스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CLP' WHERE country_name = '칠레' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CNY' WHERE country_name = '중국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '코트디부아르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XAF' WHERE country_name = '카메룬' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CDF' WHERE country_name = '콩고 민주 공화국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XAF' WHERE country_name = '콩고' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CKD' WHERE country_name = '쿡 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'COP' WHERE country_name = '콜롬비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KMF' WHERE country_name = '코모로' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CVE' WHERE country_name = '카보베르데' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CRC' WHERE country_name = '코스타리카' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CUC' WHERE country_name = '쿠바' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ANG' WHERE country_name = '퀴라소' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '크리스마스 섬' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KYD' WHERE country_name = '케이맨 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '키프로스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CZK' WHERE country_name = '체코' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '독일' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DJF' WHERE country_name = '지부티' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '도미니카 공화국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DKK' WHERE country_name = '덴마크' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DOP' WHERE country_name = '도미니카 공화국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DZD' WHERE country_name = '알제리' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '에콰도르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EGP' WHERE country_name = '이집트' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ERN' WHERE country_name = '에리트레아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DZD' WHERE country_name = '서사하라' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '스페인' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '에스토니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ETB' WHERE country_name = '에티오피아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '핀란드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'FJD' WHERE country_name = '피지' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'FKP' WHERE country_name = '포클랜드 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '프랑스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DKK' WHERE country_name = '페로 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XAF' WHERE country_name = '가봉' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GBP' WHERE country_name = '영국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GEL' WHERE country_name = '조지아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GBP' WHERE country_name = '건지 섬' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GHS' WHERE country_name = '가나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GIP' WHERE country_name = '지브롤터' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GNF' WHERE country_name = '기니' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '과들루프' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GMD' WHERE country_name = '감비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '기니비사우' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XAF' WHERE country_name = '적도 기니' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '그리스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '그레나다' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'DKK' WHERE country_name = '그린란드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GTQ' WHERE country_name = '과테말라' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '프랑스령 기아나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '괌' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GYD' WHERE country_name = '가이아나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'HKD' WHERE country_name = '홍콩' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'HNL' WHERE country_name = '온두라스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '크로아티아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'HTG' WHERE country_name = '아이티' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'HUF' WHERE country_name = '헝가리' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'IDR' WHERE country_name = '인도네시아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GBP' WHERE country_name = '맨섬' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'INR' WHERE country_name = '인도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '인도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '아일랜드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'IRR' WHERE country_name = '이란' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'IQD' WHERE country_name = '이라크' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ISK' WHERE country_name = '아이슬란드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ILS' WHERE country_name = '이스라엘' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '이탈리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'JMD' WHERE country_name = '자메이카' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'GBP' WHERE country_name = '저지 섬' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'JOD' WHERE country_name = '요르단' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'JPY' WHERE country_name = '일본' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KZT' WHERE country_name = '카자흐스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KES' WHERE country_name = '케냐' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KGS' WHERE country_name = '키르기스스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KHR' WHERE country_name = '캄보디아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '키리바시' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '세인트키츠 네비스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KRW' WHERE country_name = '한국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '코소보' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KWD' WHERE country_name = '쿠웨이트' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'LAK' WHERE country_name = '라오스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'LBP' WHERE country_name = '레바논' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'LRD' WHERE country_name = '라이베리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'LYD' WHERE country_name = '리비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '세인트루시아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'CHF' WHERE country_name = '리히텐슈타인' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'LKR' WHERE country_name = '스리랑카' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'LSL' WHERE country_name = '레소토' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '리투아니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '룩셈부르크' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '라트비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MOP' WHERE country_name = '마카오' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '생마르탱' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MAD' WHERE country_name = '모로코' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '모나코' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MDL' WHERE country_name = '몰도바' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MGA' WHERE country_name = '마다가스카르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MVR' WHERE country_name = '몰디브' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MXN' WHERE country_name = '멕시코' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '마셜 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MKD' WHERE country_name = '북마케도니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '말리' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '몰타' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MMK' WHERE country_name = '미얀마' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '몬테네그로' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MNT' WHERE country_name = '몽골국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '북마리아나 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MZN' WHERE country_name = '모잠비크' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MRU' WHERE country_name = '모리타니' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '몬트세랫' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '마르티니크' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MUR' WHERE country_name = '모리셔스' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MWK' WHERE country_name = '말라위' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'MYR' WHERE country_name = '말레이시아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '마요트' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NAD' WHERE country_name = '나미비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XPF' WHERE country_name = '누벨칼레도니' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '니제르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '노퍽 섬' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NGN' WHERE country_name = '나이지리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NIO' WHERE country_name = '니카라과' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NZD' WHERE country_name = '니우에' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '네덜란드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NOK' WHERE country_name = '노르웨이' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NPR' WHERE country_name = '네팔' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '나우루' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NZD' WHERE country_name = '뉴질랜드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'OMR' WHERE country_name = '오만' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PKR' WHERE country_name = '파키스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PAB' WHERE country_name = '파나마' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NZD' WHERE country_name = '핏케언 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PEN' WHERE country_name = '페루' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PHP' WHERE country_name = '필리핀' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '팔라우' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PGK' WHERE country_name = '파푸아뉴기니' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PLN' WHERE country_name = '폴란드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '푸에르토리코' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'KPW' WHERE country_name = '조선' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '포르투갈' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'PYG' WHERE country_name = '파라과이' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EGP' WHERE country_name = '팔레스타인' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XPF' WHERE country_name = '프랑스령 폴리네시아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'QAR' WHERE country_name = '카타르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '레위니옹' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'RON' WHERE country_name = '루마니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'RUB' WHERE country_name = '러시아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'RWF' WHERE country_name = '르완다' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SAR' WHERE country_name = '사우디아라비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SDG' WHERE country_name = '수단' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '세네갈' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SGD' WHERE country_name = '싱가포르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SHP' WHERE country_name = '조지아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NOK' WHERE country_name = '스발바르 얀마옌 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SBD' WHERE country_name = '솔로몬 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SLL' WHERE country_name = '시에라리온' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '엘살바도르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '산마리노' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SOS' WHERE country_name = '소말리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '생피에르 미클롱' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'RSD' WHERE country_name = '세르비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SSP' WHERE country_name = '남수단' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'STN' WHERE country_name = '상투메 프린시페' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SRD' WHERE country_name = '수리남' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '슬로바키아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '슬로베니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SEK' WHERE country_name = '스웨덴' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SZL' WHERE country_name = '에스와티니' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ANG' WHERE country_name = '신트마르턴' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SCR' WHERE country_name = '세이셸' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'SYP' WHERE country_name = '시리아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '터크스 케이커스 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XAF' WHERE country_name = '차드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XOF' WHERE country_name = '토고' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'THB' WHERE country_name = '태국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TJS' WHERE country_name = '타지키스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'NZD' WHERE country_name = '토켈라우' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TMT' WHERE country_name = '투르크메니스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '동티모르' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TOP' WHERE country_name = '통가' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TTD' WHERE country_name = '트리니다드 토바고' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TND' WHERE country_name = '튀니지' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TRY' WHERE country_name = '터키' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'AUD' WHERE country_name = '투발루' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TWD' WHERE country_name = '대만' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'TZS' WHERE country_name = '탄자니아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'UGX' WHERE country_name = '우간다' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'UAH' WHERE country_name = '우크라이나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '미국령 군소 제도' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'UYU' WHERE country_name = '우루과이' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '미국' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'UZS' WHERE country_name = '우즈베키스탄' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'EUR' WHERE country_name = '바티칸' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XCD' WHERE country_name = '세인트빈센트 그레나딘' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'VES' WHERE country_name = '베네수엘라' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '영국령 버진아일랜드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'USD' WHERE country_name = '미국령 버진아일랜드' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'VND' WHERE country_name = '베트남' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'VUV' WHERE country_name = '바누아투' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'XPF' WHERE country_name = '왈리스 퓌튀나' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'WST' WHERE country_name = '사모아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'YER' WHERE country_name = '예멘' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ZAR' WHERE country_name = '남아프리카' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'ZMW' WHERE country_name = '잠비아' AND currency_code IS NULL;
UPDATE country_info SET currency_code = 'BWP' WHERE country_name = '짐바브웨' AND currency_code IS NULL;