package com.example.PartTrip.util;

import java.util.HashMap;
import java.util.Map;

public class CountryCodeMapper {

    private static final Map<String, String> COUNTRY_CODE_MAP = new HashMap<>();

    static {
        COUNTRY_CODE_MAP.put("싱가포르", "SG");
        COUNTRY_CODE_MAP.put("아루바", "AW");
        COUNTRY_CODE_MAP.put("아프가니스탄", "AF");
        COUNTRY_CODE_MAP.put("앙골라", "AO");
        COUNTRY_CODE_MAP.put("앵귈라", "AI");
        COUNTRY_CODE_MAP.put("올란드 제도", "AX");
        COUNTRY_CODE_MAP.put("알바니아", "AL");
        COUNTRY_CODE_MAP.put("안도라", "AD");
        COUNTRY_CODE_MAP.put("아랍에미리트", "AE");
        COUNTRY_CODE_MAP.put("아르헨티나", "AR");
        COUNTRY_CODE_MAP.put("아르메니아", "AM");
        COUNTRY_CODE_MAP.put("아메리칸사모아", "AS");
        COUNTRY_CODE_MAP.put("남극", "AQ");
        COUNTRY_CODE_MAP.put("프랑스령 남부와 남극 지역", "TF");
        COUNTRY_CODE_MAP.put("앤티가 바부다", "AG");
        COUNTRY_CODE_MAP.put("호주", "AU");
        COUNTRY_CODE_MAP.put("오스트리아", "AT");
        COUNTRY_CODE_MAP.put("아제르바이잔", "AZ");
        COUNTRY_CODE_MAP.put("부룬디", "BI");
        COUNTRY_CODE_MAP.put("벨기에", "BE");
        COUNTRY_CODE_MAP.put("베냉", "BJ");
        COUNTRY_CODE_MAP.put("부르키나파소", "BF");
        COUNTRY_CODE_MAP.put("방글라데시", "BD");
        COUNTRY_CODE_MAP.put("불가리아", "BG");
        COUNTRY_CODE_MAP.put("바레인", "BH");
        COUNTRY_CODE_MAP.put("바하마", "BS");
        COUNTRY_CODE_MAP.put("보스니아 헤르체고비나", "BA");
        COUNTRY_CODE_MAP.put("생바르텔레미", "BL");
        COUNTRY_CODE_MAP.put("세인트헬레나", "SH");
        COUNTRY_CODE_MAP.put("벨라루스", "BY");
        COUNTRY_CODE_MAP.put("벨리즈", "BZ");
        COUNTRY_CODE_MAP.put("버뮤다", "BM");
        COUNTRY_CODE_MAP.put("볼리비아", "BO");
        COUNTRY_CODE_MAP.put("카리브 네덜란드", "BQ");
        COUNTRY_CODE_MAP.put("브라질", "BR");
        COUNTRY_CODE_MAP.put("바베이도스", "BB");
        COUNTRY_CODE_MAP.put("브루나이", "BN");
        COUNTRY_CODE_MAP.put("부탄", "BT");
        COUNTRY_CODE_MAP.put("부베 섬", "BV");
        COUNTRY_CODE_MAP.put("보츠와나", "BW");
        COUNTRY_CODE_MAP.put("중앙아프리카 공화국", "CF");
        COUNTRY_CODE_MAP.put("캐나다", "CA");
        COUNTRY_CODE_MAP.put("코코스 제도", "CC");
        COUNTRY_CODE_MAP.put("스위스", "CH");
        COUNTRY_CODE_MAP.put("칠레", "CL");
        COUNTRY_CODE_MAP.put("중국", "CN");
        COUNTRY_CODE_MAP.put("코트디부아르", "CI");
        COUNTRY_CODE_MAP.put("카메룬", "CM");
        COUNTRY_CODE_MAP.put("콩고 민주 공화국", "CD");
        COUNTRY_CODE_MAP.put("콩고", "CG");
        COUNTRY_CODE_MAP.put("쿡 제도", "CK");
        COUNTRY_CODE_MAP.put("콜롬비아", "CO");
        COUNTRY_CODE_MAP.put("코모로", "KM");
        COUNTRY_CODE_MAP.put("카보베르데", "CV");
        COUNTRY_CODE_MAP.put("코스타리카", "CR");
        COUNTRY_CODE_MAP.put("쿠바", "CU");
        COUNTRY_CODE_MAP.put("퀴라소", "CW");
        COUNTRY_CODE_MAP.put("크리스마스 섬", "CX");
        COUNTRY_CODE_MAP.put("케이맨 제도", "KY");
        COUNTRY_CODE_MAP.put("키프로스", "CY");
        COUNTRY_CODE_MAP.put("체코", "CZ");
        COUNTRY_CODE_MAP.put("독일", "DE");
        COUNTRY_CODE_MAP.put("지부티", "DJ");
        COUNTRY_CODE_MAP.put("도미니카 공화국", "DO");
        COUNTRY_CODE_MAP.put("덴마크", "DK");
        COUNTRY_CODE_MAP.put("알제리", "DZ");
        COUNTRY_CODE_MAP.put("에콰도르", "EC");
        COUNTRY_CODE_MAP.put("이집트", "EG");
        COUNTRY_CODE_MAP.put("에리트레아", "ER");
        COUNTRY_CODE_MAP.put("서사하라", "EH");
        COUNTRY_CODE_MAP.put("스페인", "ES");
        COUNTRY_CODE_MAP.put("에스토니아", "EE");
        COUNTRY_CODE_MAP.put("에티오피아", "ET");
        COUNTRY_CODE_MAP.put("핀란드", "FI");
        COUNTRY_CODE_MAP.put("피지", "FJ");
        COUNTRY_CODE_MAP.put("포클랜드 제도", "FK");
        COUNTRY_CODE_MAP.put("프랑스", "FR");
        COUNTRY_CODE_MAP.put("페로 제도", "FO");
        COUNTRY_CODE_MAP.put("미크로네시아", "FM");
        COUNTRY_CODE_MAP.put("가봉", "GA");
        COUNTRY_CODE_MAP.put("영국", "GB");
        COUNTRY_CODE_MAP.put("조지아", "GE");
        COUNTRY_CODE_MAP.put("건지 섬", "GG");
        COUNTRY_CODE_MAP.put("가나", "GH");
        COUNTRY_CODE_MAP.put("지브롤터", "GI");
        COUNTRY_CODE_MAP.put("기니", "GN");
        COUNTRY_CODE_MAP.put("과들루프", "GP");
        COUNTRY_CODE_MAP.put("감비아", "GM");
        COUNTRY_CODE_MAP.put("기니비사우", "GW");
        COUNTRY_CODE_MAP.put("적도 기니", "GQ");
        COUNTRY_CODE_MAP.put("그리스", "GR");
        COUNTRY_CODE_MAP.put("그레나다", "GD");
        COUNTRY_CODE_MAP.put("그린란드", "GL");
        COUNTRY_CODE_MAP.put("과테말라", "GT");
        COUNTRY_CODE_MAP.put("프랑스령 기아나", "GF");
        COUNTRY_CODE_MAP.put("괌", "GU");
        COUNTRY_CODE_MAP.put("가이아나", "GY");
        COUNTRY_CODE_MAP.put("홍콩", "HK");
        COUNTRY_CODE_MAP.put("허드 맥도널드 제도", "HM");
        COUNTRY_CODE_MAP.put("온두라스", "HN");
        COUNTRY_CODE_MAP.put("크로아티아", "HR");
        COUNTRY_CODE_MAP.put("아이티", "HT");
        COUNTRY_CODE_MAP.put("헝가리", "HU");
        COUNTRY_CODE_MAP.put("인도네시아", "ID");
        COUNTRY_CODE_MAP.put("맨섬", "IM");
        COUNTRY_CODE_MAP.put("인도", "IN");
        COUNTRY_CODE_MAP.put("아일랜드", "IE");
        COUNTRY_CODE_MAP.put("이란", "IR");
        COUNTRY_CODE_MAP.put("이라크", "IQ");
        COUNTRY_CODE_MAP.put("아이슬란드", "IS");
        COUNTRY_CODE_MAP.put("이스라엘", "IL");
        COUNTRY_CODE_MAP.put("이탈리아", "IT");
        COUNTRY_CODE_MAP.put("자메이카", "JM");
        COUNTRY_CODE_MAP.put("저지 섬", "JE");
        COUNTRY_CODE_MAP.put("요르단", "JO");
        COUNTRY_CODE_MAP.put("일본", "JP");
        COUNTRY_CODE_MAP.put("카자흐스탄", "KZ");
        COUNTRY_CODE_MAP.put("케냐", "KE");
        COUNTRY_CODE_MAP.put("키르기스스탄", "KG");
        COUNTRY_CODE_MAP.put("캄보디아", "KH");
        COUNTRY_CODE_MAP.put("키리바시", "KI");
        COUNTRY_CODE_MAP.put("세인트키츠 네비스", "KN");
        COUNTRY_CODE_MAP.put("한국", "KR");
        COUNTRY_CODE_MAP.put("코소보", "XK");
        COUNTRY_CODE_MAP.put("쿠웨이트", "KW");
        COUNTRY_CODE_MAP.put("라오스", "LA");
        COUNTRY_CODE_MAP.put("레바논", "LB");
        COUNTRY_CODE_MAP.put("라이베리아", "LR");
        COUNTRY_CODE_MAP.put("리비아", "LY");
        COUNTRY_CODE_MAP.put("세인트루시아", "LC");
        COUNTRY_CODE_MAP.put("리히텐슈타인", "LI");
        COUNTRY_CODE_MAP.put("스리랑카", "LK");
        COUNTRY_CODE_MAP.put("레소토", "LS");
        COUNTRY_CODE_MAP.put("리투아니아", "LT");
        COUNTRY_CODE_MAP.put("룩셈부르크", "LU");
        COUNTRY_CODE_MAP.put("라트비아", "LV");
        COUNTRY_CODE_MAP.put("마카오", "MO");
        COUNTRY_CODE_MAP.put("생마르탱", "MF");
        COUNTRY_CODE_MAP.put("모로코", "MA");
        COUNTRY_CODE_MAP.put("모나코", "MC");
        COUNTRY_CODE_MAP.put("몰도바", "MD");
        COUNTRY_CODE_MAP.put("마다가스카르", "MG");
        COUNTRY_CODE_MAP.put("몰디브", "MV");
        COUNTRY_CODE_MAP.put("멕시코", "MX");
        COUNTRY_CODE_MAP.put("마셜 제도", "MH");
        COUNTRY_CODE_MAP.put("북마케도니아", "MK");
        COUNTRY_CODE_MAP.put("말리", "ML");
        COUNTRY_CODE_MAP.put("몰타", "MT");
        COUNTRY_CODE_MAP.put("미얀마", "MM");
        COUNTRY_CODE_MAP.put("몬테네그로", "ME");
        COUNTRY_CODE_MAP.put("몽골국", "MN");
        COUNTRY_CODE_MAP.put("북마리아나 제도", "MP");
        COUNTRY_CODE_MAP.put("모잠비크", "MZ");
        COUNTRY_CODE_MAP.put("모리타니", "MR");
        COUNTRY_CODE_MAP.put("몬트세랫", "MS");
        COUNTRY_CODE_MAP.put("마르티니크", "MQ");
        COUNTRY_CODE_MAP.put("모리셔스", "MU");
        COUNTRY_CODE_MAP.put("말라위", "MW");
        COUNTRY_CODE_MAP.put("말레이시아", "MY");
        COUNTRY_CODE_MAP.put("마요트", "YT");
        COUNTRY_CODE_MAP.put("나미비아", "NA");
        COUNTRY_CODE_MAP.put("누벨칼레도니", "NC");
        COUNTRY_CODE_MAP.put("니제르", "NE");
        COUNTRY_CODE_MAP.put("노퍽 섬", "NF");
        COUNTRY_CODE_MAP.put("나이지리아", "NG");
        COUNTRY_CODE_MAP.put("니카라과", "NI");
        COUNTRY_CODE_MAP.put("니우에", "NU");
        COUNTRY_CODE_MAP.put("네덜란드", "NL");
        COUNTRY_CODE_MAP.put("노르웨이", "NO");
        COUNTRY_CODE_MAP.put("네팔", "NP");
        COUNTRY_CODE_MAP.put("나우루", "NR");
        COUNTRY_CODE_MAP.put("뉴질랜드", "NZ");
        COUNTRY_CODE_MAP.put("오만", "OM");
        COUNTRY_CODE_MAP.put("파키스탄", "PK");
        COUNTRY_CODE_MAP.put("파나마", "PA");
        COUNTRY_CODE_MAP.put("핏케언 제도", "PN");
        COUNTRY_CODE_MAP.put("페루", "PE");
        COUNTRY_CODE_MAP.put("필리핀", "PH");
        COUNTRY_CODE_MAP.put("팔라우", "PW");
        COUNTRY_CODE_MAP.put("파푸아뉴기니", "PG");
        COUNTRY_CODE_MAP.put("폴란드", "PL");
        COUNTRY_CODE_MAP.put("푸에르토리코", "PR");
        COUNTRY_CODE_MAP.put("조선", "KP");
        COUNTRY_CODE_MAP.put("포르투갈", "PT");
        COUNTRY_CODE_MAP.put("파라과이", "PY");
        COUNTRY_CODE_MAP.put("팔레스타인", "PS");
        COUNTRY_CODE_MAP.put("프랑스령 폴리네시아", "PF");
        COUNTRY_CODE_MAP.put("카타르", "QA");
        COUNTRY_CODE_MAP.put("레위니옹", "RE");
        COUNTRY_CODE_MAP.put("루마니아", "RO");
        COUNTRY_CODE_MAP.put("러시아", "RU");
        COUNTRY_CODE_MAP.put("르완다", "RW");
        COUNTRY_CODE_MAP.put("사우디아라비아", "SA");
        COUNTRY_CODE_MAP.put("수단", "SD");
        COUNTRY_CODE_MAP.put("세네갈", "SN");
        COUNTRY_CODE_MAP.put("스발바르 얀마옌 제도", "SJ");
        COUNTRY_CODE_MAP.put("솔로몬 제도", "SB");
        COUNTRY_CODE_MAP.put("시에라리온", "SL");
        COUNTRY_CODE_MAP.put("엘살바도르", "SV");
        COUNTRY_CODE_MAP.put("산마리노", "SM");
        COUNTRY_CODE_MAP.put("소말리아", "SO");
        COUNTRY_CODE_MAP.put("생피에르 미클롱", "PM");
        COUNTRY_CODE_MAP.put("세르비아", "RS");
        COUNTRY_CODE_MAP.put("남수단", "SS");
        COUNTRY_CODE_MAP.put("상투메 프린시페", "ST");
        COUNTRY_CODE_MAP.put("수리남", "SR");
        COUNTRY_CODE_MAP.put("슬로바키아", "SK");
        COUNTRY_CODE_MAP.put("슬로베니아", "SI");
        COUNTRY_CODE_MAP.put("스웨덴", "SE");
        COUNTRY_CODE_MAP.put("에스와티니", "SZ");
        COUNTRY_CODE_MAP.put("신트마르턴", "SX");
        COUNTRY_CODE_MAP.put("세이셸", "SC");
        COUNTRY_CODE_MAP.put("시리아", "SY");
        COUNTRY_CODE_MAP.put("터크스 케이커스 제도", "TC");
        COUNTRY_CODE_MAP.put("차드", "TD");
        COUNTRY_CODE_MAP.put("토고", "TG");
        COUNTRY_CODE_MAP.put("태국", "TH");
        COUNTRY_CODE_MAP.put("타지키스탄", "TJ");
        COUNTRY_CODE_MAP.put("토켈라우", "TK");
        COUNTRY_CODE_MAP.put("투르크메니스탄", "TM");
        COUNTRY_CODE_MAP.put("동티모르", "TL");
        COUNTRY_CODE_MAP.put("통가", "TO");
        COUNTRY_CODE_MAP.put("트리니다드 토바고", "TT");
        COUNTRY_CODE_MAP.put("튀니지", "TN");
        COUNTRY_CODE_MAP.put("터키", "TR");
        COUNTRY_CODE_MAP.put("투발루", "TV");
        COUNTRY_CODE_MAP.put("대만", "TW");
        COUNTRY_CODE_MAP.put("탄자니아", "TZ");
        COUNTRY_CODE_MAP.put("우간다", "UG");
        COUNTRY_CODE_MAP.put("우크라이나", "UA");
        COUNTRY_CODE_MAP.put("미국령 군소 제도", "UM");
        COUNTRY_CODE_MAP.put("우루과이", "UY");
        COUNTRY_CODE_MAP.put("미국", "US");
        COUNTRY_CODE_MAP.put("우즈베키스탄", "UZ");
        COUNTRY_CODE_MAP.put("바티칸", "VA");
        COUNTRY_CODE_MAP.put("세인트빈센트 그레나딘", "VC");
        COUNTRY_CODE_MAP.put("베네수엘라", "VE");
        COUNTRY_CODE_MAP.put("영국령 버진아일랜드", "VG");
        COUNTRY_CODE_MAP.put("미국령 버진아일랜드", "VI");
        COUNTRY_CODE_MAP.put("베트남", "VN");
        COUNTRY_CODE_MAP.put("바누아투", "VU");
        COUNTRY_CODE_MAP.put("왈리스 퓌튀나", "WF");
        COUNTRY_CODE_MAP.put("사모아", "WS");
        COUNTRY_CODE_MAP.put("예멘", "YE");
        COUNTRY_CODE_MAP.put("남아프리카", "ZA");
        COUNTRY_CODE_MAP.put("잠비아", "ZM");
        COUNTRY_CODE_MAP.put("짐바브웨", "ZW");
    }

    public static String getCountryCode(String countryName) {
        return COUNTRY_CODE_MAP.get(countryName);
    }
}
