# 축제 이름·장소 한국어 표기.
#
# 위키데이터에 ko 라벨이 없는 항목은 영어 이름이 그대로 들어온다.
# 앱에는 한국어만 보여야 해서 여기서 손으로 채운다.
# seed_festivals_public.py 가 시드를 만들 때 이 표를 먼저 본다.

TITLES = {
    "Ankos Festival": "앙코스 축제",
    "Nupe Cultural Day": "누페 문화의 날",
    "Ede-Aroh festival": "에데아로 축제",
    "Cape Town Minstrel Carnival": "케이프타운 민스트럴 카니발",
    "538 Koningsdag": "538 코닝스다흐(왕의 날)",
    "Oranje Fest": "오란여 페스트",
    "Bevrijdingspop": "해방의 날 음악축제",
    "Kukur Tihar": "쿠쿠르 티하르(개의 날)",
    "Matariki": "마타리키",
    "Founding of the Republic of China Day": "중화민국 개국기념일",
    "Taiwan Lantern Festival": "타이완 등불축제",
    "Peace Memorial Day": "평화기념일",
    "Taiwan Day Against Invasion": "타이완 침략 반대의 날",
    "National Disaster Prevention Day": "국가 방재의 날",
    "Biike Burning": "비이케 불축제",
    "Annabergfest": "안나베르크 축제",
    "Tat Cult Fest": "타트 컬트 페스트",
    "Gawai Dayak": "가와이 다약",
    "Imilchil Moussem": "이밀실 무셈",
    "National Bell Festival": "전국 종 축제",
    "Anime New Mexico": "애니메 뉴멕시코",
    "Harrisburg Independence Day Celebration": "해리스버그 독립기념일 행사",
    "Canal Winchester Labor Day Festival": "커낼윈체스터 노동절 축제",
    "Labor Day Carnival": "노동절 카니발",
    "Indigenous Peoples Day Chicago": "시카고 원주민의 날",
    "Yap Day": "얍 데이",
    "Anniversary of Duc Chi Ton": "득치똔 기념일",
    "Bal National": "발 나시오날(국민 무도회)",
    "Hololool": "홀롤로올",
    "Oruro carnival": "오루로 카니발",
    "Carnaval da Bahia": "바이아 카니발",
    "Carnaval de Pernambuco": "페르남부쿠 카니발",
    "Carnaval in Maragogipe": "마라고지피 카니발",
    "Carnival in Corumba": "코룸바 카니발",
    "Carnival in Tibagi": "치바지 카니발",
    "Carnival of Baixada Santista": "바이샤다산치스타 카니발",
    "Carnival of Olinda": "올린다 카니발",
    "Rio Music Carnival": "리우 뮤직 카니발",
    "Tiradentes Film Festival": "치라덴치스 영화제",
    "Auto de Floripes": "아우투 드 플로리페스",
    "Srefidensi Dey": "스레피덴시 데이(독립기념일)",
    "Tamborrada": "탐보라다",
    "Festivities of San Blas, Ateca": "아테카 산블라스 축제",
    "Completes de Cervera": "세르베라 콤플레테스",
    "Manresa Festival of Light": "만레사 빛 축제",
    "Moors and Christians of Alcoy": "알코이 무어인과 기독교인 축제",
    "San Prudencio festival": "산프루덴시오 축제",
    "San Isidro Day": "산이시드로 축일",
    "Corpus Christi flower carpets": "성체축일 꽃카펫 축제",
    "Falles de La Pobla de Segur": "라포블라데세구르 팔레스 축제",
    "Bonfires of Saint John in Alicante": "알리칸테 산후안 불축제",
    "Festes de Sant Joan de Ciutadella": "시우타데야 산주안 축제",
    "Les Santes": "레스산테스 축제",
    "Fiesta de la Virgen de Agosto y San Roque, Requena": "레케나 성모와 산로케 축제",
    "Festes del Tura": "투라 축제",
    "El Desarme": "엘 데사르메",
    "Fia-Faia": "피아파이아 불축제",
    "Nit dels Fatxos": "니트 델스 파초스(횃불의 밤)",
    "Festa del Pi de Centelles": "센테예스 소나무 축제",
    "Salamijada": "살라미야다(살라미 축제)",
    "Buenos Aires Carnival": "부에노스아이레스 카니발",
    "Fiesta Nacional de la Navidad": "전국 크리스마스 축제",
    # 아일랜드 pattern 은 성인 축일에 우물·성지를 순례하는 지역 축제다
    "Tullamaine Pattern": "툴러메인 패턴 축제",
    "Ullard Pattern": "울라드 패턴 축제",
    "Pattern of Tullaherin": "툴러헤린 패턴 축제",
    "Columbkille Pattern": "콜럼킬 패턴 축제",
    "Pattern of Columcille": "콜럼실 패턴 축제",
    "Kilmanagh Pattern": "킬마나 패턴 축제",
    "Pattern of Killaloe": "킬라루 패턴 축제",
    "Toberaniddaun Pattern": "토버라니던 패턴 축제",
    "Owning Pattern": "오닝 패턴 축제",
    "Newmarket Pattern": "뉴마켓 패턴 축제",
    "Brabstown Pattern": "브랩스타운 패턴 축제",
    "Kilmoganny Pattern": "킬모가니 패턴 축제",
    "Pattern of Sheestown": "시스타운 패턴 축제",
    "Pattern of Killahy": "킬라히 패턴 축제",
    "Luanda Carnival": "루안다 카니발",
    "Al Sur del Cielo": "알수르델시엘로 축제",
    "Allantide": "앨런타이드",
    "Lewes Bonfire": "루이스 본파이어 축제",
    "Montol": "몬톨 축제",
    "Rupertikirtag": "루페르티키르탁 축제",
    "Independence Day with Makhno": "마흐노와 함께하는 독립기념일",
    "Palio del Niballo": "팔리오 델 니발로",
    "Festa del grano": "밀 축제",
    "Corteggio storico": "역사 행렬 축제",
    "National Science Day": "국가 과학의 날",
    "Universal Pakhala Day": "세계 파칼라의 날",
    "Abhiruchi Sports Day": "아비루치 스포츠 데이",
    "Nanori, Shimenawa-kiri, and Fire Festival": "나노리·시메나와키리·불축제",
    "Mukonage and Suminuri": "무코나게·스미누리",
    "Atagosya no Hi Matsuri": "아타고샤 불축제",
    "Kasedori": "가세도리",
    "Gero Ta-no-Kami Festival": "게로 다노카미 축제",
    "Hiburi Kamakura": "히부리 가마쿠라",
    "omizutori": "오미즈토리",
    "Kasuga-sai": "가스가사이",
    "Emperor Jinmu Festival": "진무 천황제",
    "Chichibu Shrine Otauesai": "지치부 신사 오타우에사이",
    "Hana matsuri": "하나마쓰리(꽃축제)",
    "Takayama Festival": "다카야마 마쓰리",
    "Furukawa Festival": "후루카와 마쓰리",
    "Takaoka Mikurumayama Festival": "다카오카 미쿠루마야마 마쓰리",
    "Hakata Matsubayashi": "하카타 마쓰바야시",
    "Hiroshima Flower Festival": "히로시마 플라워 페스티벌",
    "Kamezaki Shiohi Festival": "가메자키 시오히 마쓰리",
    "Marugame Castle Festival": "마루가메성 축제",
    "Tado Festival": "다도 마쓰리",
    "Johana Hikiyama Festival": "조하나 히키야마 마쓰리",
    "Kokufu-sai": "고쿠후사이",
    "Kurayami Matsuri": "구라야미 마쓰리",
    "Miyazu Matsuri": "미야즈 마쓰리",
    "Mikuni Matsuri": "미쿠니 마쓰리",
    "Agata Matsuri": "아가타 마쓰리",
    "Otaue Shinto Service": "오타우에 신지(모내기 의식)",
    "Kangensai": "간겐사이",
    "Himeji Yukata Matsuri": "히메지 유카타 마쓰리",
    "Shimadachi Hadaka Matsuri": "시마다치 하다카 마쓰리",
    "Crow-dipper sprouts": "한게쇼(반하생)",
    "Ikutama Matsuri": "이쿠타마 마쓰리",
    "Chichibu Kawase Matsuri": "지치부 가와세 마쓰리",
    "Iida-machi Toroyama Festival": "이이다마치 도로야마 마쓰리",
    "Tsuchizaki Shinmei Shrine Festival": "쓰치자키 신메이샤 마쓰리",
    "Jizobon": "지조본",
    "Kyoto Gion Festival Yamahoko Parade": "교토 기온마쓰리 야마보코 순행",
    "Mashiko Gion Matsuri": "마시코 기온마쓰리",
    "Tanabe Matsuri": "다나베 마쓰리",
    "Kibune Matsuri": "기부네 마쓰리",
    "Hokkaido Belly Button Festival": "홋카이도 배꼽 축제",
    "Namerikawa Nebuta Nagashi": "나메리카와 네부타 나가시",
    "Sumiyoshi Matsuri": "스미요시 마쓰리",
    "Nishinippon Ohori Fireworks Festival": "니시니혼 오호리 불꽃축제",
    "Okiyo Festival": "오키요 마쓰리",
    "PL Art of Fireworks": "PL 불꽃예술 축제",
    "Hagi Summer Festival": "하기 여름축제",
    "Rice Planting Festival at Kibitsuhiko Shrine": "기비쓰히코 신사 모내기 축제",
    "Morioka Sansa Odori": "모리오카 산사오도리",
    "Chikugo River Fireworks Festival": "지쿠고강 불꽃축제",
    "Sendai Tanabata Fireworks Festival": "센다이 다나바타 불꽃축제",
    "Aomori Fireworks Display": "아오모리 불꽃축제",
    "Naruto Fireworks Festival": "나루토 불꽃축제",
    "Sendai Tanabata": "센다이 다나바타 마쓰리",
    "Anjin Festival Sea Fireworks": "안진 마쓰리 해상 불꽃축제",
    "Mikuni Fireworks Festival": "미쿠니 불꽃축제",
    "Yosakoi Matsuri": "요사코이 마쓰리",
    "Kachimai Fireworks": "가치마이 불꽃축제",
    "Sanuki Takamatsu Festival": "사누키 다카마쓰 마쓰리",
    "Fukagawa Matsuri": "후카가와 마쓰리",
    "Kujirabune Festival": "구지라부네 마쓰리",
    "Lake Suwa Fireworks Festival": "스와호 불꽃축제",
    "Nanbu Fire Festival": "난부 불축제",
    "Tomida Ishidori Matsuri": "도미다 이시도리 마쓰리",
    "Gozan no Okuribi": "고잔노오쿠리비(다이몬지 送り火)",
    "Kumano Great Fireworks Festival": "구마노 대불꽃축제",
    "Hanawa Bayashi": "하나와바야시",
    "Yokkabui": "욧카부이",
    "Shinomiya Matsuri": "시노미야 마쓰리",
    "Yoshida Fire Festival": "요시다 불축제",
    "Kaze no bon": "가제노본",
    "Tsuruga Matsuri": "쓰루가 마쓰리",
    "Kakunodate Festival": "가쿠노다테 마쓰리",
    "Nihyakuhatsuka": "니햐쿠하쓰카",
    "Iwashimizu-sai": "이와시미즈사이",
    "Okuma Kabuto Festival": "오쿠마 가부토 마쓰리",
    "Tsukurimon Festival": "쓰쿠리몬 마쓰리",
    "Sada Shin Noh": "사다 신노(사다 신사 신악)",
    "Miare Festival": "미아레 마쓰리",
    "Yahagi Shrine Autumn Grand Festival": "야하기 신사 가을 대제",
    "Sana Shrine": "사나 신사 축제",
    "Nagasaki Kunchi": "나가사키 군치",
    "Kumano Hayatama Matsuri": "구마노 하야타마 마쓰리",
    "Nada no kenka matsuri": "나다 겐카 마쓰리(싸움 축제)",
    "Inbe Shrine (Matsue City)": "이베 신사 축제(마쓰에시)",
    "Katsuyama Festival": "가쓰야마 마쓰리",
    "Kurama Himatsuri": "구라마 불축제",
    "Hakata Okunchi": "하카타 오쿤치",
    "Ueno Tenjin Festival": "우에노 덴진 마쓰리",
    "Miyazaki Shrine Grand Festival": "미야자키 신궁 대제",
    "Fujinomiya Festival": "후지노미야 마쓰리",
    "Mita festival": "미타 마쓰리",
    "Chichibu Night Festival": "지치부 요마쓰리",
    "Oku-noto no Aenokoto": "오쿠노토 아에노코토",
    "Kanji Day": "한자의 날",
    "Gishi-sai": "기시사이(의사제)",
    "Kasuga Wakamiya On-Matsuri Festival": "가스가 와카미야 온마쓰리",
    "Didgoroba": "디드고로바",
    "hanyijie": "한의절(한푸의 날)",
    "Jamhuri Day": "잠후리 데이(독립기념일)",
    "Croatian Book Day": "크로아티아 책의 날",
    "Book Night": "책의 밤",
    "Cabotage Day": "카보타주의 날",
    "Panamanian Carnival": "파나마 카니발",
    "Carnival of Lazarim": "라자림 카니발",
    "Carnival of Madeira": "마데이라 카니발",
    "Carnival of Podence": "포덴스 카니발",
    "Festival du Grand Fauconnier": "그랑 포코니에 축제",
    "Festival of Lights": "리옹 빛 축제",
    "Helsinki Day": "헬싱키의 날",
    "Debrecen Flower Carnival": "데브레첸 꽃 카니발",
    "Australia Day Live Concert": "오스트레일리아 데이 라이브 콘서트",
    "NYE In The Park": "뉴이어스이브 인 더 파크",
    "Singapore Food Festival": "싱가포르 푸드 페스티벌",
    "Fête du Vodoun": "부두교 축제",
    "El Pozón del Saladillo": "엘 포손 델 살라디요",
    "Čimburijada": "침부리야다(달걀 축제)",
    "feast of the ñatitas": "냐티타스 축제",
    "Carnaval de Brasília": "브라질리아 카니발",
    "Carnaval de Florianópolis": "플로리아노폴리스 카니발",
    "Carnival of São Paulo": "상파울루 카니발",
    "Florianópolis Gay Carnival": "플로리아노폴리스 게이 카니발",
    "Las Carantoñas, Acehúche": "아세우체 라스 카란토냐스",
    "Festes Decennals de la Mare de Déu de la Candela": "칸델라 성모 10년 축제",
    "Sant Joan Pelós": "산주안 펠로스",
    "cossiers de Pollença": "폴렌사 코시에르스 춤 축제",
    "Santiago Apóstol Festival": "성 야고보 축일 축제",
    "Cercavila de l'Imaginari de Vilanova i la Geltrú": "빌라노바 이 라 젤트루 상상 행렬",
    "Nit de l'Albà": "니트 데 랄바(새벽의 밤)",
    "Festa Major de Gràcia": "그라시아 축제",
    "cossiers de Montuïri": "몬투이리 코시에르스 춤 축제",
    "Festa Major de Vilafranca del Penedès": "빌라프랑카 델 페네데스 축제",
    "Festa de la Fil·loxera": "필록세라 축제",
    "Festivity of ‘la Mare de Déu de la Salut’ of Algemesí": "알제메시 살루드 성모 축제",
    "Semana Cervantina de Alcalá de Henares": "알칼라 데 에나레스 세르반테스 주간",
    "Dita e Verës": "여름의 날",
    "Diablada de Píllaro": "피야로 디아블라다",
    "Tōka Ebisu": "도카 에비스",
    "koshōgatsu": "고쇼가쓰(소정월)",
    "Otō Matsuri": "오토 마쓰리",
    "Hōnen Matsuri": "호넨 마쓰리",
    "Hiyoshi Sannō-sai": "히요시 산노사이",
    "Kumano Hongū Taisha Reitaisha": "구마노 혼구 대사 예대제",
    "Chiryū Festival": "지류 마쓰리",
    "Odawara Hōjō Godai Festival": "오다와라 호조 5대 마쓰리",
    "Suitengū Spring Festival": "스이텐구 봄 대제",
    "Ōgaki Festival": "오가키 마쓰리",
    "Sannō Matsuri": "산노 마쓰리",
    "HIrano'gō Natsu-matsuri": "히라노고 여름 마쓰리",
    "Ōgi Matsuri": "오기 마쓰리",
    "Jindai-ji Hōzuki Festival": "진다이지 꽈리 축제",
    "Ubagami Daijingū Togyosai": "우바가미 대신궁 도교사이",
    "Shinjō Matsuri": "신조 마쓰리",
    "Nihyakutōka": "니햐쿠토카",
    "Yatsushiro Myōken Festival": "야쓰시로 묘켄 마쓰리",
    "Akō Gishi Festival": "아코 기시 마쓰리",
    "Emperor Taishō Festival": "다이쇼 천황제",
    "Biennial of children's artistic expression": "어린이 예술 표현 비엔날레",
    "cossiers d'Algaida": "알가이다 코시에르스 춤 축제",
    "Diada del 25 d'abril": "4월 25일 기념일",
    "Sant Joan d'Alacant film festival": "산주안 데 알라칸트 영화제",
    "Montbau's patronal festival": "몬트바우 수호성인 축제",
    "St. Rioch's Pattern": "성 리오크 패턴 축제",
    "St Leonard's Well Pattern": "성 레너드 우물 패턴 축제",
    "Chinese Doctor's Day": "중국 의사의 날",
    "Torres Vedras' Carnival": "토레스베드라스 카니발",
}

LOCATIONS = {
    "Agata Shrine": "아가타 신사",
    "Alcoy": "알코이",
    "Ateca": "아테카",
    "Basilica of Santa Maria de Cervera": "세르베라 산타마리아 대성당",
    "Centelles": "센테예스",
    "Central Avenue": "센트럴 애비뉴",
    "Chichibu Shrine": "지치부 신사",
    "El Saladillo": "엘살라디요",
    "Embassy Suites Albuquerque": "앨버커키 엠버시 스위트",
    "Felanitx": "펠라니치",
    "Great Divine Temple": "까오다이 대성전",
    "Haarlemmerhout": "하를레메르하우트",
    "Hie Shrine": "히에 신사",
    "Hirano": "히라노",
    "Ikukunitama Shrine": "이쿠쿠니타마 신사",
    "Imilchil": "이밀실",
    "Jindai-ji Temple": "진다이지",
    "Kakunodate": "가쿠노다테",
    "Kamikura Shrine": "가미쿠라 신사",
    "Kamisaki Shrine": "가미사키 신사",
    "Kamo Shrine": "가모 신사",
    "Kasuga Shrine": "가스가 신사",
    "Keta Wakamiya Shrine": "게타 와카미야 신사",
    "Kibitsuhiko Shrine": "기비쓰히코 신사",
    "Kumano Hayatama Taisha": "구마노 하야타마 대사",
    "Kumano Nachi Taisha": "구마노 나치 대사",
    "La Orotava": "라오로타바",
    "La Pobla de Segur": "라포블라데세구르",
    "Maon's Well": "메이언 우물",
    "Matsunoyama Onsen": "마쓰노야마 온천",
    "Mikuni Shrine": "미쿠니 신사",
    "Mikuni Sunset Beach": "미쿠니 선셋 비치",
    "Mori Minashi Hachiman Shrine": "모리 미나시 하치만 신사",
    "Naruto Bunka Kaikan": "나루토 문화회관",
    "Nishi Park": "니시 공원",
    "Nishinomiya Shrine": "니시노미야 신사",
    "North Frisia": "북프리슬란트",
    "Olot": "올로트",
    "Onda, Sumiyoshi Taisha": "온다, 스미요시 대사",
    "Osakabe Shrine": "오사카베 신사",
    "Place du Jeu de Balle - Vossenplein": "죄드발 광장",
    "Podence": "포덴스",
    "Port of Aomori": "아오모리항",
    "Requena": "레케나",
    "Sada Shrine": "사다 신사",
    "Saint Brendan's Well": "성 브렌던 우물",
    "Saint Columbkille's Well": "성 콜럼킬 우물",
    "Saint Fiachra's Well": "성 피어크라 우물",
    "Sant Joan d'Alacant": "산주안 데 알라칸트",
    "Shichirimi Beach": "시치리미 해변",
    "St Leonard's Well": "성 레너드 우물",
    "St. Margaret's Well": "성 마거릿 우물",
    "Sugawara Shrine": "스가와라 신사",
    "Sulzbach-Rosenberg": "줄츠바흐로젠베르크",
    "Tado Taisha": "다도 대사",
    "Tagata Shrine": "다가타 신사",
    "Takaoka Sekino Shrine": "다카오카 세키노 신사",
    "Takoradi": "타코라디",
    "Three Palace Sanctuaries": "궁중삼전",
    "Tiradentes": "치라덴치스",
    "Tobermolua": "토버몰루아",
    "Tobernadaun": "토버나던",
    "Tomida": "도미다",
    "Tomioka Hachiman Shrine": "도미오카 하치만 신사",
    "Toride Shrine": "도리데 신사",
    "Tsuchizaki Shinmeisha": "쓰치자키 신메이샤",
    "Tubbernacruchnee": "터버나크루크니",
    "Tubbernamuchthee": "터버나머크티",
    "Ullard Church": "울라드 교회",
    "Victoria Park": "빅토리아 파크",
    "Yahagi Shrine": "야하기 신사",
    "Yatsushiro Shrine": "야쓰시로 신사",
    "Yuki Shrine": "유키 신사",
    "Acehúche": "아세우체",
    "Pollença": "폴렌사",
    "Vila de Gràcia": "그라시아 지구",
    "Montuïri": "몬투이리",
    "Vilafranca del Penedès": "빌라프랑카 델 페네데스",
    "Fair of Alcalá de Henares": "알칼라 데 에나레스 축제장",
    "Bagà": "바가",
    "Nigatsu-dō": "니가쓰도",
    "Kumano Hongū Taisha": "구마노 혼구 대사",
    "Chiryū Shrine": "지류 신사",
    "Ōkunitama Shrine": "오쿠니타마 신사",
    "Kurume Suitengū": "구루메 스이텐구",
    "Ōgaki Hachiman Shrine": "오가키 하치만 신사",
    "Shōman-in Temple": "쇼만인",
    "Tōkei Shrine": "도케이 신사",
    "Ōsaka Tenmangū": "오사카 덴만구",
    "Kitaguchi Hongū Fuji Sengen Shrine": "기타구치 혼구 후지센겐 신사",
    "Kenya (1963–1964)": "케냐",
}


def title(name: str) -> str:
    return TITLES.get(name, name)


def location(name: str, country_name: str) -> str:
    """위키데이터가 라벨을 안 준 장소는 Q숫자로 온다. 그럴 땐 나라 이름을 쓴다."""
    import re

    if re.fullmatch(r"Q\d+", name or ""):
        return country_name
    return LOCATIONS.get(name, name)
