# 관광지 이름·설명 한국어 표기.
#
# 구글 플레이스에서 받은 이름이라 영어·일본어·베트남어가 섞여 온다.
# 앱에는 한국어만 보여야 해서 여기서 손으로 채운다.
#
# 원칙
#  - 널리 쓰이는 한국어 표기가 있으면 그걸 쓴다 (오사카성 · 룸피니 공원)
#  - 브랜드는 한국에서 부르는 이름을 쓴다 (스타벅스 · 다이마루)
#  - 나머지는 현지 발음을 한글로 옮긴다
#  - 고유명사 뒤의 일반명사는 번역한다 (Bridge → 다리, Park → 공원)

NAMES = {
    # ── 다낭 · 숙소 ───────────────────────────────────────────
    "4Seasons Hotel": "포시즌스 호텔",
    "Alani Da Nang Hotel": "알라니 다낭 호텔",
    "Cents Da Nang Hotel": "센츠 다낭 호텔",
    "Crystal Hotel": "크리스탈 호텔",
    "Hilton Garden Inn Da Nang": "힐튼 가든 인 다낭",
    "Nghe Home - Homestay Da Nang": "응에 홈 - 다낭 홈스테이",
    "Park view": "파크 뷰",
    "RHM Luxury Hotel And Suite": "RHM 럭셔리 호텔 앤 스위트",
    "Salmalia Boutique Hotel & Spa": "살말리아 부티크 호텔 & 스파",
    "SAMDI HOTEL": "삼디 호텔",
    "Tam House Villa Hotel": "탐 하우스 빌라 호텔",
    # ── 다낭 · 액티비티 ───────────────────────────────────────
    "Công viên": "공원",
    "Công viên An Hải": "안하이 공원",
    "Công viên An Nhơn": "안년 공원",
    "Công Viên APEC": "APEC 공원",
    "Công viên Đầm Rong": "담롱 공원",
    "Công viên Hà Thân": "하턴 공원",
    "Công viên Hồ Nghinh": "호응인 공원",
    "Công viên Nguyễn Văn Linh": "응우옌반린 공원",
    "Công viên Thanh Bình": "타인빈 공원",
    "East Sea Park": "동해 공원",
    "My Khe Beach Park": "미케 해변 공원",
    "Trung tâm Giải trí Phức hợp Helio Center": "헬리오 복합 문화센터",
    # ── 다낭 · 명소 ───────────────────────────────────────────
    "Đài Tưởng niệm Liệt sỹ thành phố Đà Nẵng": "다낭 전몰용사 위령탑",
    "Dragon's Head": "용머리",
    "Dragon's Tail": "용꼬리",
    "Fresco Village Da Nang": "다낭 프레스코 빌리지",
    "Han River Bridge": "한강 다리",
    "Old River Crossing Bridge": "옛 도강교",
    "Pont main": "퐁 메인 다리",
    "Queen Cobra": "퀸 코브라",
    "Tien Son Bridge": "띠엔선 다리",
    "Tran Thi Ly Bridge": "쩐티리 다리",
    "Tượng Bồ Câu": "비둘기상",
    # ── 다낭 · 카페 ───────────────────────────────────────────
    "CaPhe Giai Khat Xiromi": "까페 지아이캇 시로미",
    "CaPhe Huy": "까페 후이",
    "Highlands Coffee": "하이랜드 커피",
    "Homie Coffee": "호미 커피",
    "Long Coffee": "롱 커피",
    "NhatHa Coffee Ice Cream": "녓하 커피 아이스크림",
    "PhoSao Coffee": "포사오 커피",
    "TigonCoffee": "띠곤 커피",
    "Trung Nguyên Coffee": "쭝응우옌 커피",
    "Trung Nguyên Legend": "쭝응우옌 레전드",
    # ── 다낭 · 맛집 · 쇼핑 ────────────────────────────────────
    "Bikini Bottom": "비키니 바텀",
    "KURUMI - Healthy Vegan Food & Desserts": "쿠루미 - 비건 푸드 & 디저트",
    "Thìa Gỗ Danang-style restaurant": "티아고 다낭식 레스토랑",
    "Minimart": "미니마트",
    "tattoo bon": "타투 본",
    # ── 방콕 · 숙소 ───────────────────────────────────────────
    "Centara Grand": "센타라 그랜드",
    "Conrad Bangkok Residences": "콘래드 방콕 레지던스",
    "Hilton Garden Inn Bangkok Riverside": "힐튼 가든 인 방콕 리버사이드",
    "Hyatt Regency Bangkok Sukhumvit": "하얏트 리젠시 방콕 수쿰빗",
    "lebua at State Tower": "르부아 앳 스테이트 타워",
    "Ruamchitt Plaza Hotel": "루암칫 플라자 호텔",
    "Tara place": "타라 플레이스",
    "The Krungkasem Srikrung Hotel": "끄룽까셈 시끄룽 호텔",
    "The Okura Prestige Bangkok Hotel": "오쿠라 프레스티지 방콕 호텔",
    "Top High Airport Link Hotel": "탑 하이 에어포트 링크 호텔",
    # ── 방콕 · 액티비티 ───────────────────────────────────────
    "Benchakitti Forest Park": "벤차키티 숲 공원",
    "Chulalongkorn University Centennial Park": "쭐랄롱꼰대학교 100주년 기념공원",
    "Lumphini Park": "룸피니 공원",
    "Maha Chetsadabodin Pavilion Court": "마하 쩨사다보딘 정자 광장",
    "Pathumwananurak Park": "빠툼와나누락 공원",
    "Sanam Luang": "사남 루앙",
    "Santi Phap Park": "산티팝 공원",
    "Saranrom Park": "사란롬 공원",
    "Suan Luang Rama VIII Park": "라마 8세 공원",
    # ── 방콕 · 명소 ───────────────────────────────────────────
    "Ananta Samakhom Throne Hall": "아난타 사마콤 궁전",
    "Ban Chao Phraya": "반 짜오프라야",
    "Bank of Thailand Museum": "태국은행 박물관",
    "Chitralada Royal Villa": "찌뜨랄라다 왕궁",
    "Devavesm Palace": "테와웻 궁전",
    "Dusit Maha Prasat Hall": "두싯 마하 쁘라삿 전각",
    "Golden Mount": "황금 산 (왓 사켓)",
    "Suan Pakkad Palace": "수언 빡깟 궁전",
    "Wang Derm Palace": "왕덤 궁전",
    # ── 방콕 · 카페 ───────────────────────────────────────────
    "Ariya": "아리야",
    "BKK Bagel Bakery": "BKK 베이글 베이커리",
    "Café Amazon": "카페 아마존",
    "Carousel Coffee": "캐러셀 커피",
    "Coffee Beans by Dao": "커피 빈스 바이 다오",
    "Floral Cafe": "플로럴 카페",
    "Gallery Drip Coffee": "갤러리 드립 커피",
    "machi machi": "마치마치",
    "Pablo Cheese Tarts!!": "파블로 치즈타르트",
    "So Heng Thai cafe": "소헹타이 카페",
    "Starbucks": "스타벅스",
    "Starbucks Coffee": "스타벅스",
    # ── 방콕 · 맛집 ───────────────────────────────────────────
    "Eat Me Restaurant": "잇미 레스토랑",
    "Fuji": "후지",
    "Karim Roti-Mataba": "까림 로띠 마따바",
    "Krua Khun Kung": "끄루아 쿤꿍",
    "Le Normandie": "르 노르망디",
    "Madame Masur": "마담 마수르",
    "MK Restaurants": "MK 레스토랑",
    "Savoey Restaurant": "사보이 레스토랑",
    "Sirocco": "시로코",
    "Spaghetti Factory": "스파게티 팩토리",
    "Vertigo Moon Bar": "버티고 문 바",
    # ── 방콕 · 쇼핑 ───────────────────────────────────────────
    "Central Silom Complex": "센트럴 실롬 콤플렉스",
    "Groove @ CentralWorld": "그루브 앳 센트럴월드",
    "Hug Thai Zone": "허그 타이 존",
    "Lam Zin Thai": "람진 타이",
    "Life Center": "라이프 센터",
    "Market Place Dusit": "마켓 플레이스 두싯",
    "Montien Mall": "몬티엔 몰",
    "MUJI": "무인양품",
    "Rain Hill": "레인 힐",
    "Robinson": "로빈슨 백화점",
    "Tokyu": "도큐 백화점",
    # ── 오사카 · 숙소 ─────────────────────────────────────────
    "Comfort Hotel Osaka Sinsaibashi": "컴포트 호텔 오사카 신사이바시",
    "Conrad Osaka": "콘래드 오사카",
    "DoubleTree by Hilton Osaka Castle": "더블트리 바이 힐튼 오사카성",
    "Hotel Granvia Osaka": "호텔 그란비아 오사카",
    "Hotel Hankyu Gran Respire Osaka": "호텔 한큐 그란 레스피레 오사카",
    "Hotel Hankyu International": "호텔 한큐 인터내셔널",
    "InterContinental Osaka": "인터컨티넨탈 오사카",
    "Osaka Marriott Miyako": "오사카 메리어트 미야코 호텔",
    "Sheraton Miyako Hotel Osaka": "쉐라톤 미야코 호텔 오사카",
    "The Ritz Carlton Osaka": "리츠칼튼 오사카",
    "The Westin Osaka": "웨스틴 오사카",
    "セントレジスホテル大阪": "세인트 레지스 호텔 오사카",
    # ── 오사카 · 액티비티 ─────────────────────────────────────
    "Horie Park": "호리에 공원",
    "Kids Plaza Osaka": "키즈 플라자 오사카",
    "Minami-Temma Park": "미나미텐마 공원",
    "Naniwa Palace Site": "나니와 궁터",
    "Nishi-Umeda Park": "니시우메다 공원",
    "Ōgimachi Park": "오기마치 공원",
    "Sanadayama Park": "사나다야마 공원",
    "Shimo-fukushima Park": "시모후쿠시마 공원",
    "Tennoji Park": "덴노지 공원",
    "浦江公園": "우라에 공원",
    # ── 오사카 · 명소 ─────────────────────────────────────────
    "Abeno Harukas Art Museum": "아베노 하루카스 미술관",
    "Kusuri Doshucho Museum": "구스리 도슈마치 자료관",
    "Mint Museum": "조폐박물관",
    "Osaka Castle Museum": "오사카성 천수각",
    "Osaka Contemporary Art Center": "오사카 현대미술센터",
    "Osaka Prefectural Museum of Kamigata Comedy and Performing Arts":
        "가미가타 연예자료관",
    # ── 오사카 · 카페 ─────────────────────────────────────────
    "Doutor Coffee Shop": "도토루 커피",
    "Gloria Jean's Coffees": "글로리아 진스 커피",
    "Good Smile × Animate Cafe": "굿스마일 × 애니메이트 카페",
    "Junkissa American": "준킷사 아메리칸",
    "Komeda's Coffee": "코메다 커피",
    "PRONTO": "프론토",
    "Salon de AmanTo": "살롱 드 아만토",
    "Seattle's Best Coffee": "시애틀스 베스트 커피",
    "Tully's Coffee": "털리스 커피",
    # ── 오사카 · 맛집 ─────────────────────────────────────────
    "CoCo ICHIBANYA": "코코이치방야",
    "Gankozushi": "간코스시",
    "Gyoza no Ohsho": "교자노오쇼",
    "Hakurien": "하쿠리엔",
    "Hanamarūdon": "하나마루우동",
    "Osaka Ohsho": "오사카 오쇼",
    "Saizeriya": "사이제리야",
    "SATO": "사토",
    "Yayoiken": "야요이켄",
    "Yukari": "유카리",
    # ── 오사카 · 쇼핑 ─────────────────────────────────────────
    "Crysta Nagahori": "크리스타 나가호리",
    "Daimaru": "다이마루 백화점",
    "Hankyu San Bangai South": "한큐 산반가이 사우스",
    "Kyobashi Coms Garden": "교바시 코무즈 가든",
    "Namba City": "난바 시티",
    "Namba Marui": "난바 마루이",
    "Takashimaya": "다카시마야 백화점",
    "上本町YUFURA": "우에혼마치 유후라",
    "京阪モール": "게이한 몰",
    "近鉄百貨店": "긴테쓰 백화점",
}

# description 의 "· xxx 요리" 자리에 들어가는 영어 낱말.
# 카페는 요리가 아니라서 문구 자체를 바꾼다(아래 describe 참고).
CUISINES = {
    "japanese": "일식",
    "chinese": "중식",
    "italian": "이탈리안",
    "french": "프렌치",
    "thai": "태국",
    "vietnamese": "베트남",
    "mediterranean": "지중해",
    "international": "다국적",
    "seafood": "해산물",
    "sushi": "초밥",
    "curry": "카레",
    "breakfast": "브런치",
    "steak house": "스테이크",
    "pasta, pizza": "파스타·피자",
    "coffee shop": "커피",
    "coffee": "커피",
    "tea": "차",
    "bubble tea": "버블티",
    "bagel": "베이글",
}


def name(place_name: str) -> str:
    """표에 없으면 원문을 그대로 둔다. 지어내지 않는다."""
    return NAMES.get(place_name, place_name)
