-- 축제 이름·장소를 한국어 표기로 바꾼다 (db/festival_ko.py 기준).
-- 이미 한국어인 행은 건드리지 않는다. 여러 번 실행해도 결과가 같다.

UPDATE festival SET title = '싱가포르 푸드 페스티벌' WHERE festival_id = 1;
UPDATE festival SET title = '앙코스 축제', location = '타코라디' WHERE festival_id = 41;
UPDATE festival SET title = '누페 문화의 날' WHERE festival_id = 42;
UPDATE festival SET title = '에데아로 축제' WHERE festival_id = 43;
UPDATE festival SET title = '케이프타운 민스트럴 카니발' WHERE festival_id = 44;
UPDATE festival SET title = '538 코닝스다흐(왕의 날)' WHERE festival_id = 45;
UPDATE festival SET title = '오란여 페스트' WHERE festival_id = 46;
UPDATE festival SET title = '해방의 날 음악축제', location = '하를레메르하우트' WHERE festival_id = 47;
UPDATE festival SET title = '쿠쿠르 티하르(개의 날)' WHERE festival_id = 48;
UPDATE festival SET title = '마타리키' WHERE festival_id = 49;
UPDATE festival SET title = '중화민국 개국기념일' WHERE festival_id = 50;
UPDATE festival SET title = '타이완 등불축제' WHERE festival_id = 51;
UPDATE festival SET title = '평화기념일' WHERE festival_id = 52;
UPDATE festival SET title = '타이완 침략 반대의 날' WHERE festival_id = 53;
UPDATE festival SET title = '국가 방재의 날' WHERE festival_id = 55;
UPDATE festival SET title = '비이케 불축제', location = '북프리슬란트' WHERE festival_id = 57;
UPDATE festival SET title = '안나베르크 축제', location = '줄츠바흐로젠베르크' WHERE festival_id = 58;
UPDATE festival SET title = '타트 컬트 페스트' WHERE festival_id = 59;
UPDATE festival SET title = '가와이 다약' WHERE festival_id = 61;
UPDATE festival SET title = '이밀실 무셈', location = '이밀실' WHERE festival_id = 62;
UPDATE festival SET title = '전국 종 축제' WHERE festival_id = 64;
UPDATE festival SET title = '애니메 뉴멕시코', location = '앨버커키 엠버시 스위트' WHERE festival_id = 65;
UPDATE festival SET title = '해리스버그 독립기념일 행사' WHERE festival_id = 66;
UPDATE festival SET title = '커낼윈체스터 노동절 축제' WHERE festival_id = 67;
UPDATE festival SET title = '노동절 카니발' WHERE festival_id = 68;
UPDATE festival SET title = '시카고 원주민의 날' WHERE festival_id = 69;
UPDATE festival SET title = '얍 데이' WHERE festival_id = 70;
UPDATE festival SET location = '엘살라디요' WHERE festival_id = 72;
UPDATE festival SET title = '득치똔 기념일', location = '까오다이 대성전' WHERE festival_id = 73;
UPDATE festival SET title = '발 나시오날(국민 무도회)', location = '죄드발 광장' WHERE festival_id = 74;
UPDATE festival SET title = '홀롤로올' WHERE festival_id = 75;
UPDATE festival SET title = '오루로 카니발' WHERE festival_id = 77;
UPDATE festival SET title = '바이아 카니발' WHERE festival_id = 79;
UPDATE festival SET title = '페르남부쿠 카니발' WHERE festival_id = 82;
UPDATE festival SET title = '마라고지피 카니발' WHERE festival_id = 83;
UPDATE festival SET title = '코룸바 카니발' WHERE festival_id = 84;
UPDATE festival SET title = '치바지 카니발' WHERE festival_id = 85;
UPDATE festival SET title = '바이샤다산치스타 카니발' WHERE festival_id = 86;
UPDATE festival SET title = '올린다 카니발' WHERE festival_id = 87;
UPDATE festival SET title = '리우 뮤직 카니발' WHERE festival_id = 90;
UPDATE festival SET title = '치라덴치스 영화제', location = '치라덴치스' WHERE festival_id = 92;
UPDATE festival SET title = '아우투 드 플로리페스' WHERE festival_id = 93;
UPDATE festival SET title = '어린이 예술 표현 비엔날레' WHERE festival_id = 94;
UPDATE festival SET title = '스레피덴시 데이(독립기념일)' WHERE festival_id = 95;
UPDATE festival SET title = '알가이다 코시에르스 춤 축제' WHERE festival_id = 96;
UPDATE festival SET title = '탐보라다' WHERE festival_id = 98;
UPDATE festival SET title = '아테카 산블라스 축제', location = '아테카' WHERE festival_id = 100;
UPDATE festival SET title = '세르베라 콤플레테스', location = '세르베라 산타마리아 대성당' WHERE festival_id = 101;
UPDATE festival SET title = '만레사 빛 축제' WHERE festival_id = 102;
UPDATE festival SET title = '알코이 무어인과 기독교인 축제', location = '알코이' WHERE festival_id = 103;
UPDATE festival SET title = '4월 25일 기념일' WHERE festival_id = 104;
UPDATE festival SET title = '산프루덴시오 축제' WHERE festival_id = 105;
UPDATE festival SET title = '산이시드로 축일' WHERE festival_id = 106;
UPDATE festival SET title = '성체축일 꽃카펫 축제', location = '라오로타바' WHERE festival_id = 107;
UPDATE festival SET title = '라포블라데세구르 팔레스 축제', location = '라포블라데세구르' WHERE festival_id = 108;
UPDATE festival SET title = '알리칸테 산후안 불축제' WHERE festival_id = 109;
UPDATE festival SET title = '시우타데야 산주안 축제' WHERE festival_id = 110;
UPDATE festival SET location = '펠라니치' WHERE festival_id = 111;
UPDATE festival SET title = '산주안 데 알라칸트 영화제', location = '산주안 데 알라칸트' WHERE festival_id = 112;
UPDATE festival SET title = '레스산테스 축제' WHERE festival_id = 116;
UPDATE festival SET title = '레케나 성모와 산로케 축제', location = '레케나' WHERE festival_id = 120;
UPDATE festival SET title = '투라 축제', location = '올로트' WHERE festival_id = 124;
UPDATE festival SET title = '몬트바우 수호성인 축제' WHERE festival_id = 126;
UPDATE festival SET title = '엘 데사르메' WHERE festival_id = 128;
UPDATE festival SET title = '피아파이아 불축제' WHERE festival_id = 129;
UPDATE festival SET title = '니트 델스 파초스(횃불의 밤)' WHERE festival_id = 130;
UPDATE festival SET title = '센테예스 소나무 축제', location = '센테예스' WHERE festival_id = 131;
UPDATE festival SET title = '살라미야다(살라미 축제)' WHERE festival_id = 132;
UPDATE festival SET title = '부에노스아이레스 카니발' WHERE festival_id = 133;
UPDATE festival SET title = '전국 크리스마스 축제' WHERE festival_id = 134;
UPDATE festival SET title = '툴러메인 패턴 축제', location = '메이언 우물' WHERE festival_id = 135;
UPDATE festival SET title = '울라드 패턴 축제', location = '울라드 교회' WHERE festival_id = 136;
UPDATE festival SET title = '툴러헤린 패턴 축제' WHERE festival_id = 137;
UPDATE festival SET title = '콜럼킬 패턴 축제', location = '성 콜럼킬 우물' WHERE festival_id = 138;
UPDATE festival SET title = '콜럼실 패턴 축제', location = '성 콜럼킬 우물' WHERE festival_id = 139;
UPDATE festival SET title = '킬마나 패턴 축제' WHERE festival_id = 140;
UPDATE festival SET title = '킬라루 패턴 축제', location = '토버몰루아' WHERE festival_id = 141;
UPDATE festival SET title = '토버라니던 패턴 축제', location = '토버나던' WHERE festival_id = 142;
UPDATE festival SET title = '성 리오크 패턴 축제' WHERE festival_id = 143;
UPDATE festival SET title = '오닝 패턴 축제', location = '터버나머크티' WHERE festival_id = 144;
UPDATE festival SET title = '뉴마켓 패턴 축제', location = '성 브렌던 우물' WHERE festival_id = 145;
UPDATE festival SET title = '브랩스타운 패턴 축제', location = '성 마거릿 우물' WHERE festival_id = 146;
UPDATE festival SET title = '킬모가니 패턴 축제' WHERE festival_id = 147;
UPDATE festival SET title = '시스타운 패턴 축제', location = '성 피어크라 우물' WHERE festival_id = 148;
UPDATE festival SET title = '킬라히 패턴 축제', location = '터버나크루크니' WHERE festival_id = 149;
UPDATE festival SET title = '성 레너드 우물 패턴 축제', location = '성 레너드 우물' WHERE festival_id = 150;
UPDATE festival SET title = '루안다 카니발' WHERE festival_id = 152;
UPDATE festival SET title = '알수르델시엘로 축제' WHERE festival_id = 154;
UPDATE festival SET title = '앨런타이드' WHERE festival_id = 155;
UPDATE festival SET title = '루이스 본파이어 축제' WHERE festival_id = 156;
UPDATE festival SET title = '몬톨 축제' WHERE festival_id = 157;
UPDATE festival SET title = '루페르티키르탁 축제' WHERE festival_id = 158;
UPDATE festival SET title = '마흐노와 함께하는 독립기념일' WHERE festival_id = 159;
UPDATE festival SET title = '팔리오 델 니발로', location = '이탈리아' WHERE festival_id = 161;
UPDATE festival SET title = '밀 축제' WHERE festival_id = 162;
UPDATE festival SET title = '역사 행렬 축제' WHERE festival_id = 163;
UPDATE festival SET title = '국가 과학의 날' WHERE festival_id = 164;
UPDATE festival SET title = '세계 파칼라의 날' WHERE festival_id = 165;
UPDATE festival SET title = '아비루치 스포츠 데이' WHERE festival_id = 166;
UPDATE festival SET title = '가와이 다약' WHERE festival_id = 167;
UPDATE festival SET title = '나노리·시메나와키리·불축제' WHERE festival_id = 168;
UPDATE festival SET location = '니시노미야 신사' WHERE festival_id = 169;
UPDATE festival SET title = '무코나게·스미누리', location = '마쓰노야마 온천' WHERE festival_id = 170;
UPDATE festival SET title = '아타고샤 불축제' WHERE festival_id = 172;
UPDATE festival SET location = '가미쿠라 신사' WHERE festival_id = 174;
UPDATE festival SET title = '가세도리' WHERE festival_id = 175;
UPDATE festival SET title = '게로 다노카미 축제', location = '모리 미나시 하치만 신사' WHERE festival_id = 176;
UPDATE festival SET title = '히부리 가마쿠라', location = '가쿠노다테' WHERE festival_id = 177;
UPDATE festival SET title = '오미즈토리' WHERE festival_id = 179;
UPDATE festival SET title = '가스가사이' WHERE festival_id = 180;
UPDATE festival SET location = '다가타 신사' WHERE festival_id = 181;
UPDATE festival SET title = '진무 천황제', location = '궁중삼전' WHERE festival_id = 182;
UPDATE festival SET title = '지치부 신사 오타우에사이', location = '지치부 신사' WHERE festival_id = 183;
UPDATE festival SET title = '하나마쓰리(꽃축제)' WHERE festival_id = 184;
UPDATE festival SET title = '다카야마 마쓰리', location = '히에 신사' WHERE festival_id = 187;
UPDATE festival SET title = '후루카와 마쓰리', location = '게타 와카미야 신사' WHERE festival_id = 188;
UPDATE festival SET title = '다카오카 미쿠루마야마 마쓰리', location = '다카오카 세키노 신사' WHERE festival_id = 189;
UPDATE festival SET title = '하카타 마쓰바야시' WHERE festival_id = 191;
UPDATE festival SET title = '히로시마 플라워 페스티벌' WHERE festival_id = 192;
UPDATE festival SET title = '가메자키 시오히 마쓰리', location = '가미사키 신사' WHERE festival_id = 193;
UPDATE festival SET title = '마루가메성 축제' WHERE festival_id = 194;
UPDATE festival SET title = '다도 마쓰리', location = '다도 대사' WHERE festival_id = 197;
UPDATE festival SET title = '조하나 히키야마 마쓰리' WHERE festival_id = 198;
UPDATE festival SET title = '고쿠후사이' WHERE festival_id = 199;
UPDATE festival SET title = '구라야미 마쓰리' WHERE festival_id = 200;
UPDATE festival SET title = '미야즈 마쓰리' WHERE festival_id = 203;
UPDATE festival SET location = '가모 신사' WHERE festival_id = 205;
UPDATE festival SET title = '미쿠니 마쓰리', location = '미쿠니 신사' WHERE festival_id = 206;
UPDATE festival SET location = '히에 신사' WHERE festival_id = 207;
UPDATE festival SET title = '아가타 마쓰리', location = '아가타 신사' WHERE festival_id = 208;
UPDATE festival SET title = '오타우에 신지(모내기 의식)', location = '온다, 스미요시 대사' WHERE festival_id = 209;
UPDATE festival SET title = '간겐사이' WHERE festival_id = 210;
UPDATE festival SET title = '히메지 유카타 마쓰리', location = '오사카베 신사' WHERE festival_id = 211;
UPDATE festival SET title = '시마다치 하다카 마쓰리' WHERE festival_id = 212;
UPDATE festival SET title = '한게쇼(반하생)' WHERE festival_id = 214;
UPDATE festival SET title = '이쿠타마 마쓰리', location = '이쿠쿠니타마 신사' WHERE festival_id = 217;
UPDATE festival SET location = '히라노' WHERE festival_id = 218;
UPDATE festival SET location = '구마노 나치 대사' WHERE festival_id = 219;
UPDATE festival SET title = '지치부 가와세 마쓰리', location = '지치부 신사' WHERE festival_id = 220;
UPDATE festival SET location = '진다이지' WHERE festival_id = 221;
UPDATE festival SET title = '이이다마치 도로야마 마쓰리', location = '가스가 신사' WHERE festival_id = 222;
UPDATE festival SET title = '쓰치자키 신메이샤 마쓰리', location = '쓰치자키 신메이샤' WHERE festival_id = 223;
UPDATE festival SET title = '지조본' WHERE festival_id = 224;
UPDATE festival SET title = '교토 기온마쓰리 야마보코 순행' WHERE festival_id = 225;
UPDATE festival SET title = '마시코 기온마쓰리' WHERE festival_id = 226;
UPDATE festival SET title = '다나베 마쓰리' WHERE festival_id = 227;
UPDATE festival SET title = '기부네 마쓰리' WHERE festival_id = 229;
UPDATE festival SET title = '홋카이도 배꼽 축제' WHERE festival_id = 230;
UPDATE festival SET title = '나메리카와 네부타 나가시' WHERE festival_id = 231;
UPDATE festival SET title = '스미요시 마쓰리' WHERE festival_id = 232;
UPDATE festival SET title = '니시니혼 오호리 불꽃축제' WHERE festival_id = 233;
UPDATE festival SET title = '오키요 마쓰리' WHERE festival_id = 234;
UPDATE festival SET title = 'PL 불꽃예술 축제' WHERE festival_id = 235;
UPDATE festival SET title = '하기 여름축제' WHERE festival_id = 236;
UPDATE festival SET title = '기비쓰히코 신사 모내기 축제', location = '기비쓰히코 신사' WHERE festival_id = 237;
UPDATE festival SET title = '모리오카 산사오도리', location = '센트럴 애비뉴' WHERE festival_id = 238;
UPDATE festival SET title = '지쿠고강 불꽃축제' WHERE festival_id = 239;
UPDATE festival SET title = '센다이 다나바타 불꽃축제', location = '니시 공원' WHERE festival_id = 240;
UPDATE festival SET title = '아오모리 불꽃축제', location = '아오모리항' WHERE festival_id = 242;
UPDATE festival SET title = '나루토 불꽃축제', location = '나루토 문화회관' WHERE festival_id = 243;
UPDATE festival SET title = '센다이 다나바타 마쓰리' WHERE festival_id = 244;
UPDATE festival SET title = '안진 마쓰리 해상 불꽃축제' WHERE festival_id = 245;
UPDATE festival SET title = '미쿠니 불꽃축제', location = '미쿠니 선셋 비치' WHERE festival_id = 246;
UPDATE festival SET title = '요사코이 마쓰리' WHERE festival_id = 248;
UPDATE festival SET title = '가치마이 불꽃축제' WHERE festival_id = 249;
UPDATE festival SET title = '사누키 다카마쓰 마쓰리' WHERE festival_id = 250;
UPDATE festival SET title = '후카가와 마쓰리', location = '도미오카 하치만 신사' WHERE festival_id = 251;
UPDATE festival SET title = '구지라부네 마쓰리', location = '도리데 신사' WHERE festival_id = 252;
UPDATE festival SET title = '스와호 불꽃축제' WHERE festival_id = 253;
UPDATE festival SET title = '난부 불축제' WHERE festival_id = 254;
UPDATE festival SET title = '도미다 이시도리 마쓰리', location = '도미다' WHERE festival_id = 255;
UPDATE festival SET title = '고잔노오쿠리비(다이몬지 送り火)' WHERE festival_id = 256;
UPDATE festival SET title = '구마노 대불꽃축제', location = '시치리미 해변' WHERE festival_id = 257;
UPDATE festival SET title = '하나와바야시' WHERE festival_id = 258;
UPDATE festival SET title = '욧카부이' WHERE festival_id = 259;
UPDATE festival SET title = '시노미야 마쓰리' WHERE festival_id = 260;
UPDATE festival SET title = '요시다 불축제' WHERE festival_id = 262;
UPDATE festival SET title = '가제노본' WHERE festival_id = 264;
UPDATE festival SET title = '쓰루가 마쓰리', location = '일본' WHERE festival_id = 265;
UPDATE festival SET title = '가쿠노다테 마쓰리', location = '가쿠노다테' WHERE festival_id = 266;
UPDATE festival SET title = '니햐쿠하쓰카' WHERE festival_id = 267;
UPDATE festival SET title = '이와시미즈사이' WHERE festival_id = 268;
UPDATE festival SET title = '오쿠마 가부토 마쓰리' WHERE festival_id = 269;
UPDATE festival SET title = '쓰쿠리몬 마쓰리' WHERE festival_id = 270;
UPDATE festival SET title = '사다 신노(사다 신사 신악)', location = '사다 신사' WHERE festival_id = 271;
UPDATE festival SET title = '미아레 마쓰리' WHERE festival_id = 272;
UPDATE festival SET title = '야하기 신사 가을 대제', location = '야하기 신사' WHERE festival_id = 273;
UPDATE festival SET title = '사나 신사 축제' WHERE festival_id = 274;
UPDATE festival SET title = '나가사키 군치' WHERE festival_id = 275;
UPDATE festival SET title = '구마노 하야타마 마쓰리', location = '구마노 하야타마 대사' WHERE festival_id = 276;
UPDATE festival SET title = '나다 겐카 마쓰리(싸움 축제)' WHERE festival_id = 277;
UPDATE festival SET title = '이베 신사 축제(마쓰에시)' WHERE festival_id = 278;
UPDATE festival SET title = '가쓰야마 마쓰리' WHERE festival_id = 279;
UPDATE festival SET title = '구라마 불축제', location = '유키 신사' WHERE festival_id = 280;
UPDATE festival SET title = '하카타 오쿤치' WHERE festival_id = 282;
UPDATE festival SET title = '우에노 덴진 마쓰리', location = '스가와라 신사' WHERE festival_id = 283;
UPDATE festival SET title = '미야자키 신궁 대제' WHERE festival_id = 284;
UPDATE festival SET title = '후지노미야 마쓰리' WHERE festival_id = 286;
UPDATE festival SET title = '미타 마쓰리' WHERE festival_id = 288;
UPDATE festival SET location = '야쓰시로 신사' WHERE festival_id = 289;
UPDATE festival SET title = '지치부 요마쓰리', location = '지치부 신사' WHERE festival_id = 290;
UPDATE festival SET title = '오쿠노토 아에노코토' WHERE festival_id = 291;
UPDATE festival SET title = '한자의 날' WHERE festival_id = 292;
UPDATE festival SET title = '기시사이(의사제)' WHERE festival_id = 294;
UPDATE festival SET title = '가스가 와카미야 온마쓰리' WHERE festival_id = 295;
UPDATE festival SET title = '디드고로바' WHERE festival_id = 297;
UPDATE festival SET title = '중국 의사의 날' WHERE festival_id = 301;
UPDATE festival SET title = '한의절(한푸의 날)' WHERE festival_id = 303;
UPDATE festival SET title = '잠후리 데이(독립기념일)' WHERE festival_id = 304;
UPDATE festival SET title = '크로아티아 책의 날' WHERE festival_id = 305;
UPDATE festival SET title = '책의 밤' WHERE festival_id = 306;
UPDATE festival SET title = '카보타주의 날' WHERE festival_id = 307;
UPDATE festival SET title = '파나마 카니발' WHERE festival_id = 308;
UPDATE festival SET title = '라자림 카니발' WHERE festival_id = 309;
UPDATE festival SET title = '마데이라 카니발' WHERE festival_id = 310;
UPDATE festival SET title = '포덴스 카니발', location = '포덴스' WHERE festival_id = 311;
UPDATE festival SET title = '토레스베드라스 카니발' WHERE festival_id = 312;
UPDATE festival SET title = '그랑 포코니에 축제' WHERE festival_id = 313;
UPDATE festival SET title = '리옹 빛 축제' WHERE festival_id = 314;
UPDATE festival SET title = '헬싱키의 날' WHERE festival_id = 315;
UPDATE festival SET title = '데브레첸 꽃 카니발' WHERE festival_id = 318;
UPDATE festival SET title = '오스트레일리아 데이 라이브 콘서트' WHERE festival_id = 319;
UPDATE festival SET title = '오란여 페스트' WHERE festival_id = 320;
UPDATE festival SET title = '뉴이어스이브 인 더 파크', location = '빅토리아 파크' WHERE festival_id = 321;
UPDATE festival SET title = '부두교 축제' WHERE festival_id = 71;
UPDATE festival SET title = '엘 포손 델 살라디요' WHERE festival_id = 72;
UPDATE festival SET title = '침부리야다(달걀 축제)' WHERE festival_id = 76;
UPDATE festival SET title = '냐티타스 축제' WHERE festival_id = 78;
UPDATE festival SET title = '브라질리아 카니발' WHERE festival_id = 80;
UPDATE festival SET title = '플로리아노폴리스 카니발' WHERE festival_id = 81;
UPDATE festival SET title = '상파울루 카니발' WHERE festival_id = 88;
UPDATE festival SET title = '플로리아노폴리스 게이 카니발' WHERE festival_id = 89;
UPDATE festival SET title = '아세우체 라스 카란토냐스', location = '아세우체' WHERE festival_id = 97;
UPDATE festival SET title = '칸델라 성모 10년 축제' WHERE festival_id = 99;
UPDATE festival SET title = '산주안 펠로스' WHERE festival_id = 111;
UPDATE festival SET title = '폴렌사 코시에르스 춤 축제', location = '폴렌사' WHERE festival_id = 113;
UPDATE festival SET title = '성 야고보 축일 축제' WHERE festival_id = 115;
UPDATE festival SET title = '빌라노바 이 라 젤트루 상상 행렬' WHERE festival_id = 117;
UPDATE festival SET title = '니트 데 랄바(새벽의 밤)' WHERE festival_id = 118;
UPDATE festival SET title = '그라시아 축제', location = '그라시아 지구' WHERE festival_id = 119;
UPDATE festival SET title = '몬투이리 코시에르스 춤 축제', location = '몬투이리' WHERE festival_id = 121;
UPDATE festival SET title = '빌라프랑카 델 페네데스 축제', location = '빌라프랑카 델 페네데스' WHERE festival_id = 122;
UPDATE festival SET title = '필록세라 축제' WHERE festival_id = 123;
UPDATE festival SET title = '알제메시 살루드 성모 축제' WHERE festival_id = 125;
UPDATE festival SET title = '알칼라 데 에나레스 세르반테스 주간', location = '알칼라 데 에나레스 축제장' WHERE festival_id = 127;
UPDATE festival SET location = '바가' WHERE festival_id = 129;
UPDATE festival SET title = '여름의 날' WHERE festival_id = 151;
UPDATE festival SET title = '피야로 디아블라다' WHERE festival_id = 153;
UPDATE festival SET title = '도카 에비스' WHERE festival_id = 169;
UPDATE festival SET title = '고쇼가쓰(소정월)' WHERE festival_id = 171;
UPDATE festival SET title = '오토 마쓰리' WHERE festival_id = 174;
UPDATE festival SET location = '니가쓰도' WHERE festival_id = 179;
UPDATE festival SET title = '호넨 마쓰리' WHERE festival_id = 181;
UPDATE festival SET title = '히요시 산노사이' WHERE festival_id = 185;
UPDATE festival SET title = '구마노 혼구 대사 예대제', location = '구마노 혼구 대사' WHERE festival_id = 186;
UPDATE festival SET title = '지류 마쓰리', location = '지류 신사' WHERE festival_id = 190;
UPDATE festival SET title = '오다와라 호조 5대 마쓰리' WHERE festival_id = 195;
UPDATE festival SET location = '오쿠니타마 신사' WHERE festival_id = 200;
UPDATE festival SET title = '스이텐구 봄 대제', location = '구루메 스이텐구' WHERE festival_id = 201;
UPDATE festival SET title = '오가키 마쓰리', location = '오가키 하치만 신사' WHERE festival_id = 204;
UPDATE festival SET title = '산노 마쓰리' WHERE festival_id = 207;
UPDATE festival SET location = '쇼만인' WHERE festival_id = 213;
UPDATE festival SET title = '히라노고 여름 마쓰리' WHERE festival_id = 218;
UPDATE festival SET title = '오기 마쓰리' WHERE festival_id = 219;
UPDATE festival SET title = '진다이지 꽈리 축제' WHERE festival_id = 221;
UPDATE festival SET location = '도케이 신사' WHERE festival_id = 227;
UPDATE festival SET location = '오사카 덴만구' WHERE festival_id = 228;
UPDATE festival SET title = '우바가미 대신궁 도교사이' WHERE festival_id = 247;
UPDATE festival SET title = '신조 마쓰리' WHERE festival_id = 261;
UPDATE festival SET location = '기타구치 혼구 후지센겐 신사' WHERE festival_id = 262;
UPDATE festival SET title = '니햐쿠토카' WHERE festival_id = 263;
UPDATE festival SET title = '야쓰시로 묘켄 마쓰리' WHERE festival_id = 289;
UPDATE festival SET title = '아코 기시 마쓰리' WHERE festival_id = 293;
UPDATE festival SET title = '다이쇼 천황제' WHERE festival_id = 296;
UPDATE festival SET location = '케냐' WHERE festival_id = 304;
