-- 관광지 이름·설명·주소 한국어 표기 (2026-08-30 적용)
--
-- db/tour_place_ko.py 의 표로 만든 문장이다. 이미 적용했고, 다른 환경의
-- DB 를 같은 상태로 맞출 때 쓴다. 시드를 새로 돌리면 스크립트가
-- 같은 표를 보므로 이 파일을 다시 돌릴 필요는 없다.
--
-- 베트남어·태국어 주소는 일부러 두었다. 현지 표기여야 택시나 지도에서
-- 쓸 수 있다. 일본어 주소는 한자라 읽기 어려워 한글로 바꿨다.

update tour_place set description='오사카의 맛집 · 해산물' where tour_place_id=6;
update tour_place set place_name='사이제리야', description='오사카의 맛집 · 이탈리안', address='오사카부 오사카시 주오구 17' where tour_place_id=8;
update tour_place set place_name='유카리', description='오사카의 맛집 · 일식' where tour_place_id=9;
update tour_place set place_name='교자노오쇼', description='오사카의 맛집 · 중식' where tour_place_id=10;
update tour_place set place_name='간코스시', description='오사카의 맛집 · 초밥' where tour_place_id=11;
update tour_place set place_name='사토', description='오사카의 맛집 · 일식' where tour_place_id=12;
update tour_place set place_name='코코이치방야', description='오사카의 맛집 · 카레' where tour_place_id=13;
update tour_place set place_name='하쿠리엔', description='오사카의 맛집 · 중식' where tour_place_id=14;
update tour_place set place_name='오사카 오쇼', description='오사카의 맛집 · 일식' where tour_place_id=15;
update tour_place set place_name='야요이켄', description='오사카의 맛집 · 일식' where tour_place_id=16;
update tour_place set place_name='하나마루우동', description='오사카의 맛집 · 일식' where tour_place_id=17;
update tour_place set address='오사카부 오사카시 주오구 1' where tour_place_id=18;
update tour_place set address='오사카시이쿠노구 이쿠노구' where tour_place_id=20;
update tour_place set place_name='아베노 하루카스 미술관', address='오사카부 오사카시 아베노구 24' where tour_place_id=24;
update tour_place set place_name='조폐박물관' where tour_place_id=25;
update tour_place set place_name='오사카성 천수각' where tour_place_id=26;
update tour_place set place_name='구스리 도슈마치 자료관' where tour_place_id=27;
update tour_place set place_name='오사카 현대미술센터' where tour_place_id=28;
update tour_place set place_name='가미가타 연예자료관' where tour_place_id=29;
update tour_place set place_name='오사카 메리어트 미야코 호텔', address='오사카부 오사카시 아베노구 43' where tour_place_id=30;
update tour_place set place_name='호텔 그란비아 오사카' where tour_place_id=31;
update tour_place set place_name='쉐라톤 미야코 호텔 오사카' where tour_place_id=32;
update tour_place set place_name='더블트리 바이 힐튼 오사카성', address='오사카부 오사카시 주오구 1' where tour_place_id=33;
update tour_place set place_name='호텔 한큐 그란 레스피레 오사카' where tour_place_id=34;
update tour_place set place_name='리츠칼튼 오사카' where tour_place_id=35;
update tour_place set place_name='호텔 한큐 인터내셔널' where tour_place_id=36;
update tour_place set place_name='인터컨티넨탈 오사카' where tour_place_id=37;
update tour_place set place_name='컴포트 호텔 오사카 신사이바시' where tour_place_id=38;
update tour_place set place_name='웨스틴 오사카' where tour_place_id=39;
update tour_place set place_name='콘래드 오사카', address='오사카부 오사카시 기타구 4' where tour_place_id=40;
update tour_place set place_name='세인트 레지스 호텔 오사카' where tour_place_id=41;
update tour_place set description='오사카의 카페 · 커피' where tour_place_id=42;
update tour_place set description='오사카의 카페 · 커피' where tour_place_id=43;
update tour_place set place_name='스타벅스', description='오사카의 카페 · 커피' where tour_place_id=44;
update tour_place set place_name='프론토', description='오사카의 카페 · 커피', address='오사카시주오구시로미2-1-6' where tour_place_id=45;
update tour_place set place_name='도토루 커피', description='오사카의 카페 · 커피', address='오사카부오사카시 주오구신사이바시스지１초메 ２−１６' where tour_place_id=46;
update tour_place set place_name='살롱 드 아만토', address='오사카시 기타구 26' where tour_place_id=47;
update tour_place set place_name='글로리아 진스 커피', description='오사카의 카페 · 커피', address='오사카시주오구시로미1-3-7 시로미도리' where tour_place_id=48;
update tour_place set place_name='굿스마일 × 애니메이트 카페', address='오사카부 오사카시 나니와구 17' where tour_place_id=49;
update tour_place set place_name='코메다 커피', description='오사카의 카페 · 커피' where tour_place_id=50;
update tour_place set place_name='준킷사 아메리칸', description='오사카의 카페 · 커피', address='오사카부 오사카시 주오구' where tour_place_id=51;
update tour_place set place_name='시애틀스 베스트 커피', address='오사카시주오구시로미1-4-27 시로미도리' where tour_place_id=52;
update tour_place set place_name='털리스 커피', description='오사카의 카페 · 커피' where tour_place_id=53;
update tour_place set place_name='키즈 플라자 오사카', address='오사카부 오사카시 기타구 7' where tour_place_id=56;
update tour_place set place_name='덴노지 공원' where tour_place_id=57;
update tour_place set place_name='미나미텐마 공원' where tour_place_id=58;
update tour_place set place_name='나니와 궁터' where tour_place_id=59;
update tour_place set place_name='시모후쿠시마 공원' where tour_place_id=60;
update tour_place set place_name='오기마치 공원' where tour_place_id=61;
update tour_place set place_name='사나다야마 공원' where tour_place_id=62;
update tour_place set place_name='니시우메다 공원' where tour_place_id=63;
update tour_place set place_name='우라에 공원' where tour_place_id=64;
update tour_place set place_name='호리에 공원' where tour_place_id=65;
update tour_place set place_name='다카시마야 백화점' where tour_place_id=68;
update tour_place set place_name='다이마루 백화점' where tour_place_id=69;
update tour_place set place_name='한큐 산반가이 사우스' where tour_place_id=70;
update tour_place set place_name='크리스타 나가호리' where tour_place_id=71;
update tour_place set place_name='난바 시티' where tour_place_id=72;
update tour_place set place_name='게이한 몰' where tour_place_id=73;
update tour_place set place_name='우에혼마치 유후라' where tour_place_id=74;
update tour_place set place_name='난바 마루이' where tour_place_id=75;
update tour_place set place_name='교바시 코무즈 가든' where tour_place_id=76;
update tour_place set place_name='긴테쓰 백화점', address='오사카부 오사카시 아베노구 43' where tour_place_id=77;
update tour_place set place_name='시로코', description='방콕의 맛집 · 지중해' where tour_place_id=78;
update tour_place set place_name='르 노르망디', description='방콕의 맛집 · 프렌치 · 2성급' where tour_place_id=79;
update tour_place set description='방콕의 맛집 · 태국' where tour_place_id=80;
update tour_place set place_name='사보이 레스토랑', description='방콕의 맛집 · 태국' where tour_place_id=81;
update tour_place set place_name='MK 레스토랑', description='방콕의 맛집 · 태국' where tour_place_id=82;
update tour_place set place_name='까림 로띠 마따바' where tour_place_id=83;
update tour_place set place_name='후지', description='방콕의 맛집 · 일식' where tour_place_id=84;
update tour_place set place_name='잇미 레스토랑', description='방콕의 맛집 · 다국적' where tour_place_id=85;
update tour_place set place_name='버티고 문 바' where tour_place_id=86;
update tour_place set place_name='스파게티 팩토리', description='방콕의 맛집 · 파스타·피자' where tour_place_id=87;
update tour_place set place_name='마담 마수르' where tour_place_id=88;
update tour_place set place_name='끄루아 쿤꿍', description='방콕의 맛집 · 태국' where tour_place_id=89;
update tour_place set place_name='테와웻 궁전' where tour_place_id=93;
update tour_place set place_name='왕덤 궁전' where tour_place_id=94;
update tour_place set place_name='아난타 사마콤 궁전' where tour_place_id=95;
update tour_place set place_name='황금 산 (왓 사켓)' where tour_place_id=96;
update tour_place set place_name='태국은행 박물관' where tour_place_id=97;
update tour_place set place_name='수언 빡깟 궁전' where tour_place_id=98;
update tour_place set place_name='두싯 마하 쁘라삿 전각' where tour_place_id=99;
update tour_place set place_name='반 짜오프라야' where tour_place_id=100;
update tour_place set place_name='찌뜨랄라다 왕궁' where tour_place_id=101;
update tour_place set place_name='센타라 그랜드' where tour_place_id=102;
update tour_place set place_name='르부아 앳 스테이트 타워' where tour_place_id=103;
update tour_place set place_name='콘래드 방콕 레지던스' where tour_place_id=105;
update tour_place set place_name='오쿠라 프레스티지 방콕 호텔' where tour_place_id=106;
update tour_place set place_name='힐튼 가든 인 방콕 리버사이드' where tour_place_id=107;
update tour_place set place_name='하얏트 리젠시 방콕 수쿰빗' where tour_place_id=109;
update tour_place set place_name='탑 하이 에어포트 링크 호텔' where tour_place_id=110;
update tour_place set place_name='루암칫 플라자 호텔' where tour_place_id=111;
update tour_place set place_name='끄룽까셈 시끄룽 호텔' where tour_place_id=112;
update tour_place set place_name='타라 플레이스' where tour_place_id=113;
update tour_place set place_name='BKK 베이글 베이커리', description='방콕의 카페 · 베이글' where tour_place_id=114;
update tour_place set place_name='스타벅스', description='방콕의 카페 · 커피' where tour_place_id=115;
update tour_place set place_name='스타벅스', description='방콕의 카페 · 커피' where tour_place_id=116;
update tour_place set place_name='카페 아마존', description='방콕의 카페 · 커피' where tour_place_id=117;
update tour_place set place_name='파블로 치즈타르트', description='방콕의 카페 · 커피' where tour_place_id=118;
update tour_place set place_name='소헹타이 카페', description='방콕의 카페 · 커피' where tour_place_id=119;
update tour_place set place_name='아리야' where tour_place_id=120;
update tour_place set place_name='마치마치', description='방콕의 카페 · 버블티' where tour_place_id=121;
update tour_place set place_name='갤러리 드립 커피', description='방콕의 카페 · 커피' where tour_place_id=122;
update tour_place set place_name='플로럴 카페', description='방콕의 카페 · 차' where tour_place_id=123;
update tour_place set place_name='캐러셀 커피', description='방콕의 카페 · 커피' where tour_place_id=124;
update tour_place set place_name='커피 빈스 바이 다오', description='방콕의 카페 · 태국' where tour_place_id=125;
update tour_place set place_name='사란롬 공원' where tour_place_id=129;
update tour_place set place_name='산티팝 공원' where tour_place_id=130;
update tour_place set place_name='룸피니 공원' where tour_place_id=131;
update tour_place set place_name='라마 8세 공원' where tour_place_id=132;
update tour_place set place_name='벤차키티 숲 공원' where tour_place_id=133;
update tour_place set place_name='사남 루앙' where tour_place_id=134;
update tour_place set place_name='빠툼와나누락 공원' where tour_place_id=135;
update tour_place set place_name='쭐랄롱꼰대학교 100주년 기념공원' where tour_place_id=136;
update tour_place set place_name='마하 쩨사다보딘 정자 광장' where tour_place_id=137;
update tour_place set place_name='도큐 백화점' where tour_place_id=138;
update tour_place set place_name='마켓 플레이스 두싯' where tour_place_id=140;
update tour_place set place_name='라이프 센터' where tour_place_id=141;
update tour_place set place_name='센트럴 실롬 콤플렉스' where tour_place_id=142;
update tour_place set place_name='람진 타이' where tour_place_id=143;
update tour_place set place_name='레인 힐' where tour_place_id=144;
update tour_place set place_name='몬티엔 몰' where tour_place_id=145;
update tour_place set place_name='무인양품' where tour_place_id=146;
update tour_place set place_name='로빈슨 백화점' where tour_place_id=147;
update tour_place set place_name='그루브 앳 센트럴월드' where tour_place_id=148;
update tour_place set place_name='허그 타이 존' where tour_place_id=149;
update tour_place set description='다낭의 맛집 · 베트남' where tour_place_id=150;
update tour_place set description='다낭의 맛집 · 베트남' where tour_place_id=151;
update tour_place set description='다낭의 맛집 · 해산물' where tour_place_id=152;
update tour_place set description='다낭의 맛집 · 스테이크' where tour_place_id=153;
update tour_place set description='다낭의 맛집 · 베트남' where tour_place_id=154;
update tour_place set place_name='비키니 바텀', description='다낭의 맛집 · 브런치' where tour_place_id=157;
update tour_place set place_name='쿠루미 - 비건 푸드 & 디저트', description='다낭의 맛집 · 브런치' where tour_place_id=158;
update tour_place set description='다낭의 맛집 · 베트남' where tour_place_id=159;
update tour_place set description='다낭의 맛집 · 해산물' where tour_place_id=160;
update tour_place set place_name='티아고 다낭식 레스토랑', description='다낭의 맛집 · 베트남' where tour_place_id=161;
update tour_place set place_name='용머리' where tour_place_id=163;
update tour_place set place_name='쩐티리 다리' where tour_place_id=164;
update tour_place set place_name='띠엔선 다리' where tour_place_id=165;
update tour_place set place_name='한강 다리' where tour_place_id=166;
update tour_place set place_name='옛 도강교' where tour_place_id=167;
update tour_place set place_name='다낭 프레스코 빌리지' where tour_place_id=168;
update tour_place set place_name='퀸 코브라' where tour_place_id=169;
update tour_place set place_name='다낭 전몰용사 위령탑' where tour_place_id=170;
update tour_place set place_name='퐁 메인 다리' where tour_place_id=171;
update tour_place set place_name='용꼬리' where tour_place_id=172;
update tour_place set place_name='비둘기상' where tour_place_id=173;
update tour_place set place_name='탐 하우스 빌라 호텔' where tour_place_id=175;
update tour_place set place_name='크리스탈 호텔' where tour_place_id=176;
update tour_place set place_name='포시즌스 호텔' where tour_place_id=177;
update tour_place set place_name='힐튼 가든 인 다낭' where tour_place_id=178;
update tour_place set place_name='응에 홈 - 다낭 홈스테이' where tour_place_id=179;
update tour_place set place_name='알라니 다낭 호텔' where tour_place_id=180;
update tour_place set place_name='센츠 다낭 호텔' where tour_place_id=181;
update tour_place set place_name='RHM 럭셔리 호텔 앤 스위트' where tour_place_id=182;
update tour_place set place_name='살말리아 부티크 호텔 & 스파' where tour_place_id=183;
update tour_place set place_name='파크 뷰' where tour_place_id=184;
update tour_place set place_name='삼디 호텔' where tour_place_id=185;
update tour_place set place_name='하이랜드 커피', description='다낭의 카페 · 커피' where tour_place_id=186;
update tour_place set place_name='쭝응우옌 커피', description='다낭의 카페 · 커피' where tour_place_id=188;
update tour_place set place_name='롱 커피', description='다낭의 카페 · 커피' where tour_place_id=189;
update tour_place set place_name='쭝응우옌 레전드' where tour_place_id=190;
update tour_place set place_name='호미 커피' where tour_place_id=191;
update tour_place set place_name='녓하 커피 아이스크림' where tour_place_id=192;
update tour_place set place_name='까페 후이' where tour_place_id=193;
update tour_place set place_name='까페 지아이캇 시로미' where tour_place_id=194;
update tour_place set place_name='포사오 커피' where tour_place_id=195;
update tour_place set place_name='띠곤 커피' where tour_place_id=196;
update tour_place set place_name='동해 공원' where tour_place_id=197;
update tour_place set place_name='헬리오 복합 문화센터' where tour_place_id=198;
update tour_place set place_name='미케 해변 공원' where tour_place_id=199;
update tour_place set place_name='응우옌반린 공원' where tour_place_id=200;
update tour_place set place_name='공원' where tour_place_id=201;
update tour_place set place_name='APEC 공원' where tour_place_id=202;
update tour_place set place_name='담롱 공원' where tour_place_id=203;
update tour_place set place_name='타인빈 공원' where tour_place_id=204;
update tour_place set place_name='하턴 공원' where tour_place_id=205;
update tour_place set place_name='안하이 공원' where tour_place_id=206;
update tour_place set place_name='안년 공원' where tour_place_id=207;
update tour_place set place_name='호응인 공원' where tour_place_id=208;
update tour_place set place_name='미니마트' where tour_place_id=209;
update tour_place set place_name='타투 본' where tour_place_id=210;

-- 확정된 여행 카드는 장소 이름을 복사해 들고 있다. 함께 바꾼다.
update trip_card_place set place_name='포시즌스 호텔' where place_name='4Seasons Hotel';
update trip_card_place set place_name='알라니 다낭 호텔' where place_name='Alani Da Nang Hotel';
update trip_card_place set place_name='센츠 다낭 호텔' where place_name='Cents Da Nang Hotel';
update trip_card_place set place_name='크리스탈 호텔' where place_name='Crystal Hotel';
update trip_card_place set place_name='힐튼 가든 인 다낭' where place_name='Hilton Garden Inn Da Nang';
update trip_card_place set place_name='응에 홈 - 다낭 홈스테이' where place_name='Nghe Home - Homestay Da Nang';
update trip_card_place set place_name='파크 뷰' where place_name='Park view';
update trip_card_place set place_name='RHM 럭셔리 호텔 앤 스위트' where place_name='RHM Luxury Hotel And Suite';
update trip_card_place set place_name='살말리아 부티크 호텔 & 스파' where place_name='Salmalia Boutique Hotel & Spa';
update trip_card_place set place_name='삼디 호텔' where place_name='SAMDI HOTEL';
update trip_card_place set place_name='탐 하우스 빌라 호텔' where place_name='Tam House Villa Hotel';
update trip_card_place set place_name='공원' where place_name='Công viên';
update trip_card_place set place_name='안하이 공원' where place_name='Công viên An Hải';
update trip_card_place set place_name='안년 공원' where place_name='Công viên An Nhơn';
update trip_card_place set place_name='APEC 공원' where place_name='Công Viên APEC';
update trip_card_place set place_name='담롱 공원' where place_name='Công viên Đầm Rong';
update trip_card_place set place_name='하턴 공원' where place_name='Công viên Hà Thân';
update trip_card_place set place_name='호응인 공원' where place_name='Công viên Hồ Nghinh';
update trip_card_place set place_name='응우옌반린 공원' where place_name='Công viên Nguyễn Văn Linh';
update trip_card_place set place_name='타인빈 공원' where place_name='Công viên Thanh Bình';
update trip_card_place set place_name='동해 공원' where place_name='East Sea Park';
update trip_card_place set place_name='미케 해변 공원' where place_name='My Khe Beach Park';
update trip_card_place set place_name='헬리오 복합 문화센터' where place_name='Trung tâm Giải trí Phức hợp Helio Center';
update trip_card_place set place_name='다낭 전몰용사 위령탑' where place_name='Đài Tưởng niệm Liệt sỹ thành phố Đà Nẵng';
update trip_card_place set place_name='용머리' where place_name='Dragon''s Head';
update trip_card_place set place_name='용꼬리' where place_name='Dragon''s Tail';
update trip_card_place set place_name='다낭 프레스코 빌리지' where place_name='Fresco Village Da Nang';
update trip_card_place set place_name='한강 다리' where place_name='Han River Bridge';
update trip_card_place set place_name='옛 도강교' where place_name='Old River Crossing Bridge';
update trip_card_place set place_name='퐁 메인 다리' where place_name='Pont main';
update trip_card_place set place_name='퀸 코브라' where place_name='Queen Cobra';
update trip_card_place set place_name='띠엔선 다리' where place_name='Tien Son Bridge';
update trip_card_place set place_name='쩐티리 다리' where place_name='Tran Thi Ly Bridge';
update trip_card_place set place_name='비둘기상' where place_name='Tượng Bồ Câu';
update trip_card_place set place_name='까페 지아이캇 시로미' where place_name='CaPhe Giai Khat Xiromi';
update trip_card_place set place_name='까페 후이' where place_name='CaPhe Huy';
update trip_card_place set place_name='하이랜드 커피' where place_name='Highlands Coffee';
update trip_card_place set place_name='호미 커피' where place_name='Homie Coffee';
update trip_card_place set place_name='롱 커피' where place_name='Long Coffee';
update trip_card_place set place_name='녓하 커피 아이스크림' where place_name='NhatHa Coffee Ice Cream';
update trip_card_place set place_name='포사오 커피' where place_name='PhoSao Coffee';
update trip_card_place set place_name='띠곤 커피' where place_name='TigonCoffee';
update trip_card_place set place_name='쭝응우옌 커피' where place_name='Trung Nguyên Coffee';
update trip_card_place set place_name='쭝응우옌 레전드' where place_name='Trung Nguyên Legend';
update trip_card_place set place_name='비키니 바텀' where place_name='Bikini Bottom';
update trip_card_place set place_name='쿠루미 - 비건 푸드 & 디저트' where place_name='KURUMI - Healthy Vegan Food & Desserts';
update trip_card_place set place_name='티아고 다낭식 레스토랑' where place_name='Thìa Gỗ Danang-style restaurant';
update trip_card_place set place_name='미니마트' where place_name='Minimart';
update trip_card_place set place_name='타투 본' where place_name='tattoo bon';
update trip_card_place set place_name='센타라 그랜드' where place_name='Centara Grand';
update trip_card_place set place_name='콘래드 방콕 레지던스' where place_name='Conrad Bangkok Residences';
update trip_card_place set place_name='힐튼 가든 인 방콕 리버사이드' where place_name='Hilton Garden Inn Bangkok Riverside';
update trip_card_place set place_name='하얏트 리젠시 방콕 수쿰빗' where place_name='Hyatt Regency Bangkok Sukhumvit';
update trip_card_place set place_name='르부아 앳 스테이트 타워' where place_name='lebua at State Tower';
update trip_card_place set place_name='루암칫 플라자 호텔' where place_name='Ruamchitt Plaza Hotel';
update trip_card_place set place_name='타라 플레이스' where place_name='Tara place';
update trip_card_place set place_name='끄룽까셈 시끄룽 호텔' where place_name='The Krungkasem Srikrung Hotel';
update trip_card_place set place_name='오쿠라 프레스티지 방콕 호텔' where place_name='The Okura Prestige Bangkok Hotel';
update trip_card_place set place_name='탑 하이 에어포트 링크 호텔' where place_name='Top High Airport Link Hotel';
update trip_card_place set place_name='벤차키티 숲 공원' where place_name='Benchakitti Forest Park';
update trip_card_place set place_name='쭐랄롱꼰대학교 100주년 기념공원' where place_name='Chulalongkorn University Centennial Park';
update trip_card_place set place_name='룸피니 공원' where place_name='Lumphini Park';
update trip_card_place set place_name='마하 쩨사다보딘 정자 광장' where place_name='Maha Chetsadabodin Pavilion Court';
update trip_card_place set place_name='빠툼와나누락 공원' where place_name='Pathumwananurak Park';
update trip_card_place set place_name='사남 루앙' where place_name='Sanam Luang';
update trip_card_place set place_name='산티팝 공원' where place_name='Santi Phap Park';
update trip_card_place set place_name='사란롬 공원' where place_name='Saranrom Park';
update trip_card_place set place_name='라마 8세 공원' where place_name='Suan Luang Rama VIII Park';
update trip_card_place set place_name='아난타 사마콤 궁전' where place_name='Ananta Samakhom Throne Hall';
update trip_card_place set place_name='반 짜오프라야' where place_name='Ban Chao Phraya';
update trip_card_place set place_name='태국은행 박물관' where place_name='Bank of Thailand Museum';
update trip_card_place set place_name='찌뜨랄라다 왕궁' where place_name='Chitralada Royal Villa';
update trip_card_place set place_name='테와웻 궁전' where place_name='Devavesm Palace';
update trip_card_place set place_name='두싯 마하 쁘라삿 전각' where place_name='Dusit Maha Prasat Hall';
update trip_card_place set place_name='황금 산 (왓 사켓)' where place_name='Golden Mount';
update trip_card_place set place_name='수언 빡깟 궁전' where place_name='Suan Pakkad Palace';
update trip_card_place set place_name='왕덤 궁전' where place_name='Wang Derm Palace';
update trip_card_place set place_name='아리야' where place_name='Ariya';
update trip_card_place set place_name='BKK 베이글 베이커리' where place_name='BKK Bagel Bakery';
update trip_card_place set place_name='카페 아마존' where place_name='Café Amazon';
update trip_card_place set place_name='캐러셀 커피' where place_name='Carousel Coffee';
update trip_card_place set place_name='커피 빈스 바이 다오' where place_name='Coffee Beans by Dao';
update trip_card_place set place_name='플로럴 카페' where place_name='Floral Cafe';
update trip_card_place set place_name='갤러리 드립 커피' where place_name='Gallery Drip Coffee';
update trip_card_place set place_name='마치마치' where place_name='machi machi';
update trip_card_place set place_name='파블로 치즈타르트' where place_name='Pablo Cheese Tarts!!';
update trip_card_place set place_name='소헹타이 카페' where place_name='So Heng Thai cafe';
update trip_card_place set place_name='스타벅스' where place_name='Starbucks';
update trip_card_place set place_name='스타벅스' where place_name='Starbucks Coffee';
update trip_card_place set place_name='잇미 레스토랑' where place_name='Eat Me Restaurant';
update trip_card_place set place_name='후지' where place_name='Fuji';
update trip_card_place set place_name='까림 로띠 마따바' where place_name='Karim Roti-Mataba';
update trip_card_place set place_name='끄루아 쿤꿍' where place_name='Krua Khun Kung';
update trip_card_place set place_name='르 노르망디' where place_name='Le Normandie';
update trip_card_place set place_name='마담 마수르' where place_name='Madame Masur';
update trip_card_place set place_name='MK 레스토랑' where place_name='MK Restaurants';
update trip_card_place set place_name='사보이 레스토랑' where place_name='Savoey Restaurant';
update trip_card_place set place_name='시로코' where place_name='Sirocco';
update trip_card_place set place_name='스파게티 팩토리' where place_name='Spaghetti Factory';
update trip_card_place set place_name='버티고 문 바' where place_name='Vertigo Moon Bar';
update trip_card_place set place_name='센트럴 실롬 콤플렉스' where place_name='Central Silom Complex';
update trip_card_place set place_name='그루브 앳 센트럴월드' where place_name='Groove @ CentralWorld';
update trip_card_place set place_name='허그 타이 존' where place_name='Hug Thai Zone';
update trip_card_place set place_name='람진 타이' where place_name='Lam Zin Thai';
update trip_card_place set place_name='라이프 센터' where place_name='Life Center';
update trip_card_place set place_name='마켓 플레이스 두싯' where place_name='Market Place Dusit';
update trip_card_place set place_name='몬티엔 몰' where place_name='Montien Mall';
update trip_card_place set place_name='무인양품' where place_name='MUJI';
update trip_card_place set place_name='레인 힐' where place_name='Rain Hill';
update trip_card_place set place_name='로빈슨 백화점' where place_name='Robinson';
update trip_card_place set place_name='도큐 백화점' where place_name='Tokyu';
update trip_card_place set place_name='컴포트 호텔 오사카 신사이바시' where place_name='Comfort Hotel Osaka Sinsaibashi';
update trip_card_place set place_name='콘래드 오사카' where place_name='Conrad Osaka';
update trip_card_place set place_name='더블트리 바이 힐튼 오사카성' where place_name='DoubleTree by Hilton Osaka Castle';
update trip_card_place set place_name='호텔 그란비아 오사카' where place_name='Hotel Granvia Osaka';
update trip_card_place set place_name='호텔 한큐 그란 레스피레 오사카' where place_name='Hotel Hankyu Gran Respire Osaka';
update trip_card_place set place_name='호텔 한큐 인터내셔널' where place_name='Hotel Hankyu International';
update trip_card_place set place_name='인터컨티넨탈 오사카' where place_name='InterContinental Osaka';
update trip_card_place set place_name='오사카 메리어트 미야코 호텔' where place_name='Osaka Marriott Miyako';
update trip_card_place set place_name='쉐라톤 미야코 호텔 오사카' where place_name='Sheraton Miyako Hotel Osaka';
update trip_card_place set place_name='리츠칼튼 오사카' where place_name='The Ritz Carlton Osaka';
update trip_card_place set place_name='웨스틴 오사카' where place_name='The Westin Osaka';
update trip_card_place set place_name='세인트 레지스 호텔 오사카' where place_name='セントレジスホテル大阪';
update trip_card_place set place_name='호리에 공원' where place_name='Horie Park';
update trip_card_place set place_name='키즈 플라자 오사카' where place_name='Kids Plaza Osaka';
update trip_card_place set place_name='미나미텐마 공원' where place_name='Minami-Temma Park';
update trip_card_place set place_name='나니와 궁터' where place_name='Naniwa Palace Site';
update trip_card_place set place_name='니시우메다 공원' where place_name='Nishi-Umeda Park';
update trip_card_place set place_name='오기마치 공원' where place_name='Ōgimachi Park';
update trip_card_place set place_name='사나다야마 공원' where place_name='Sanadayama Park';
update trip_card_place set place_name='시모후쿠시마 공원' where place_name='Shimo-fukushima Park';
update trip_card_place set place_name='덴노지 공원' where place_name='Tennoji Park';
update trip_card_place set place_name='우라에 공원' where place_name='浦江公園';
update trip_card_place set place_name='아베노 하루카스 미술관' where place_name='Abeno Harukas Art Museum';
update trip_card_place set place_name='구스리 도슈마치 자료관' where place_name='Kusuri Doshucho Museum';
update trip_card_place set place_name='조폐박물관' where place_name='Mint Museum';
update trip_card_place set place_name='오사카성 천수각' where place_name='Osaka Castle Museum';
update trip_card_place set place_name='오사카 현대미술센터' where place_name='Osaka Contemporary Art Center';
update trip_card_place set place_name='가미가타 연예자료관' where place_name='Osaka Prefectural Museum of Kamigata Comedy and Performing Arts';
update trip_card_place set place_name='도토루 커피' where place_name='Doutor Coffee Shop';
update trip_card_place set place_name='글로리아 진스 커피' where place_name='Gloria Jean''s Coffees';
update trip_card_place set place_name='굿스마일 × 애니메이트 카페' where place_name='Good Smile × Animate Cafe';
update trip_card_place set place_name='준킷사 아메리칸' where place_name='Junkissa American';
update trip_card_place set place_name='코메다 커피' where place_name='Komeda''s Coffee';
update trip_card_place set place_name='프론토' where place_name='PRONTO';
update trip_card_place set place_name='살롱 드 아만토' where place_name='Salon de AmanTo';
update trip_card_place set place_name='시애틀스 베스트 커피' where place_name='Seattle''s Best Coffee';
update trip_card_place set place_name='털리스 커피' where place_name='Tully''s Coffee';
update trip_card_place set place_name='코코이치방야' where place_name='CoCo ICHIBANYA';
update trip_card_place set place_name='간코스시' where place_name='Gankozushi';
update trip_card_place set place_name='교자노오쇼' where place_name='Gyoza no Ohsho';
update trip_card_place set place_name='하쿠리엔' where place_name='Hakurien';
update trip_card_place set place_name='하나마루우동' where place_name='Hanamarūdon';
update trip_card_place set place_name='오사카 오쇼' where place_name='Osaka Ohsho';
update trip_card_place set place_name='사이제리야' where place_name='Saizeriya';
update trip_card_place set place_name='사토' where place_name='SATO';
update trip_card_place set place_name='야요이켄' where place_name='Yayoiken';
update trip_card_place set place_name='유카리' where place_name='Yukari';
update trip_card_place set place_name='크리스타 나가호리' where place_name='Crysta Nagahori';
update trip_card_place set place_name='다이마루 백화점' where place_name='Daimaru';
update trip_card_place set place_name='한큐 산반가이 사우스' where place_name='Hankyu San Bangai South';
update trip_card_place set place_name='교바시 코무즈 가든' where place_name='Kyobashi Coms Garden';
update trip_card_place set place_name='난바 시티' where place_name='Namba City';
update trip_card_place set place_name='난바 마루이' where place_name='Namba Marui';
update trip_card_place set place_name='다카시마야 백화점' where place_name='Takashimaya';
update trip_card_place set place_name='우에혼마치 유후라' where place_name='上本町YUFURA';
update trip_card_place set place_name='게이한 몰' where place_name='京阪モール';
update trip_card_place set place_name='긴테쓰 백화점' where place_name='近鉄百貨店';
